
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Mar 17 2026 20:44:39 IST (Mar 17 2026 15:14:39 UTC)

// Verification Directory fv/asynchronous_fifo 

module asynchronous_fifo(wclk, rclk, rst, w_en, r_en, data_in,
     data_out, full, empty, scan_en, scan_in, scan_out, DFT_sdi_1,
     DFT_sdo_1);
  input wclk, rclk, rst, w_en, r_en, scan_en, scan_in, DFT_sdi_1;
  input [7:0] data_in;
  output [7:0] data_out;
  output full, empty, scan_out, DFT_sdo_1;
  wire wclk, rclk, rst, w_en, r_en, scan_en, scan_in, DFT_sdi_1;
  wire [7:0] data_in;
  wire [7:0] data_out;
  wire full, empty, scan_out, DFT_sdo_1;
  wire [6:0] b_wptr;
  wire [6:0] b_rptr;
  wire [6:0] g_wptr_sync;
  wire [6:0] g_rptr_sync;
  wire [6:0] g_wptr;
  wire [6:0] g_rptr;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130;
  FIFO_Memory_DEPTH64_DATA_WIDTH8_PTR_WIDTH6 fifom(.wclk (wclk), .w_en
       (w_en), .rclk (rclk), .r_en (r_en), .b_wptr (b_wptr), .b_rptr
       (b_rptr), .din (data_in), .full (full), .empty (empty), .dout
       (data_out));
  CLKINVX1 g394(.A (rst), .Y (n_6));
  SDFFQX1 rptr_h_empty_reg(.CK (rclk), .D (n_130), .SI (b_rptr[6]), .SE
       (scan_en), .Q (empty));
  SDFFQX1 wptr_h_full_reg(.CK (wclk), .D (n_129), .SI (b_wptr[6]), .SE
       (scan_en), .Q (full));
  NOR2XL g1100__2398(.A (n_6), .B (n_128), .Y (n_130));
  NOR2XL g1101__5107(.A (n_127), .B (n_6), .Y (n_129));
  NAND4XL g1102__6260(.A (n_106), .B (n_122), .C (n_126), .D (n_120),
       .Y (n_128));
  NAND4XL g1103__4319(.A (n_105), .B (n_121), .C (n_125), .D (n_119),
       .Y (n_127));
  OAI21XL g1104__8428(.A0 (g_wptr_sync[5]), .A1 (n_109), .B0 (n_124),
       .Y (n_126));
  OAI21XL g1105__5526(.A0 (g_rptr_sync[5]), .A1 (n_110), .B0 (n_123),
       .Y (n_125));
  NAND2XL g1106__6783(.A (g_wptr_sync[5]), .B (n_109), .Y (n_124));
  NAND2XL g1107__3680(.A (g_rptr_sync[5]), .B (n_110), .Y (n_123));
  OAI21XL g1108__1617(.A0 (g_wptr_sync[4]), .A1 (n_96), .B0 (n_118), .Y
       (n_122));
  SDFFRHQX1 \sync_wptr_dout_reg[5] (.RN (rst), .CK (rclk), .D
       (g_wptr[5]), .SI (g_wptr_sync[4]), .SE (scan_en), .Q
       (g_wptr_sync[5]));
  SDFFRHQX1 \sync_rptr_dout_reg[5] (.RN (rst), .CK (wclk), .D
       (g_rptr[5]), .SI (g_rptr_sync[4]), .SE (scan_en), .Q
       (g_rptr_sync[5]));
  OAI21XL g1111__2802(.A0 (g_rptr_sync[4]), .A1 (n_95), .B0 (n_117), .Y
       (n_121));
  AOI211X1 g1112__1705(.A0 (g_wptr_sync[1]), .A1 (n_49), .B0 (n_68),
       .C0 (n_116), .Y (n_120));
  AOI211X1 g1113__5122(.A0 (g_rptr_sync[1]), .A1 (n_48), .B0 (n_67),
       .C0 (n_115), .Y (n_119));
  SDFFQXL \rptr_h_g_rptr_reg[5] (.CK (rclk), .D (n_113), .SI
       (g_rptr[4]), .SE (scan_en), .Q (g_rptr[5]));
  SDFFQXL \wptr_h_g_wptr_reg[5] (.CK (wclk), .D (n_114), .SI
       (g_wptr[4]), .SE (scan_en), .Q (g_wptr[5]));
  NAND2XL g1116__8246(.A (g_wptr_sync[4]), .B (n_96), .Y (n_118));
  NAND2XL g1117__7098(.A (g_rptr_sync[4]), .B (n_95), .Y (n_117));
  OAI211X1 g1118__6131(.A0 (g_wptr_sync[0]), .A1 (n_36), .B0 (n_53),
       .C0 (n_112), .Y (n_116));
  OAI211X1 g1119__1881(.A0 (g_rptr_sync[0]), .A1 (n_35), .B0 (n_52),
       .C0 (n_111), .Y (n_115));
  NOR2XL g1120__5115(.A (n_110), .B (n_5), .Y (n_114));
  SDFFRHQX1 \sync_wptr_dout_reg[4] (.RN (rst), .CK (rclk), .D
       (g_wptr[4]), .SI (g_wptr_sync[3]), .SE (scan_en), .Q
       (g_wptr_sync[4]));
  SDFFRHQX1 \sync_rptr_dout_reg[4] (.RN (rst), .CK (wclk), .D
       (g_rptr[4]), .SI (g_rptr_sync[3]), .SE (scan_en), .Q
       (g_rptr_sync[4]));
  AND2XL g1123__7482(.A (rst), .B (n_109), .Y (n_113));
  NOR2XL g1124__4733(.A (n_84), .B (n_107), .Y (n_112));
  NOR2XL g1125__6161(.A (n_85), .B (n_108), .Y (n_111));
  SDFFQX1 \wptr_h_g_wptr_reg[6] (.CK (wclk), .D (n_101), .SI
       (g_wptr[5]), .SE (scan_en), .Q (DFT_sdo_1));
  SDFFQXL \rptr_h_g_rptr_reg[4] (.CK (rclk), .D (n_98), .SI
       (g_rptr[3]), .SE (scan_en), .Q (g_rptr[4]));
  SDFFQX1 \rptr_h_g_rptr_reg[6] (.CK (rclk), .D (n_99), .SI
       (g_rptr[5]), .SE (scan_en), .Q (g_rptr[6]));
  SDFFQX1 \rptr_h_b_rptr_reg[6] (.CK (rclk), .D (n_100), .SI
       (b_rptr[5]), .SE (scan_en), .Q (b_rptr[6]));
  SDFFQXL \wptr_h_g_wptr_reg[4] (.CK (wclk), .D (n_104), .SI
       (g_wptr[3]), .SE (scan_en), .Q (g_wptr[4]));
  SDFFQX1 \wptr_h_b_wptr_reg[6] (.CK (wclk), .D (n_97), .SI
       (b_wptr[5]), .SE (scan_en), .Q (b_wptr[6]));
  AOI21XL g1132__9315(.A0 (g_rptr_sync[3]), .A1 (n_78), .B0 (n_103), .Y
       (n_108));
  AOI21XL g1133__9945(.A0 (g_wptr_sync[3]), .A1 (n_79), .B0 (n_102), .Y
       (n_107));
  MXI2XL g1134__2883(.A (n_94), .B (n_93), .S0 (scan_out), .Y (n_106));
  MXI2XL g1135__2346(.A (n_92), .B (n_91), .S0 (g_rptr_sync[6]), .Y
       (n_105));
  MXI2XL g1136__1666(.A (n_92), .B (n_91), .S0 (n_77), .Y (n_110));
  MXI2XL g1137__7410(.A (n_93), .B (n_94), .S0 (n_76), .Y (n_109));
  AND2XL g1138__6417(.A (n_95), .B (rst), .Y (n_104));
  NOR2XL g1139__5477(.A (g_rptr_sync[3]), .B (n_78), .Y (n_103));
  NOR2XL g1140__2398(.A (g_wptr_sync[3]), .B (n_79), .Y (n_102));
  NOR2XL g1141__5107(.A (n_92), .B (n_6), .Y (n_101));
  NOR2XL g1142__6260(.A (n_7), .B (n_93), .Y (n_100));
  NOR2XL g1143__4319(.A (n_5), .B (n_93), .Y (n_99));
  AND2XL g1144__8428(.A (rst), .B (n_96), .Y (n_98));
  NOR2XL g1145__5526(.A (n_92), .B (n_5), .Y (n_97));
  SDFFQX1 \rptr_h_b_rptr_reg[5] (.CK (rclk), .D (n_4), .SI (b_rptr[4]),
       .SE (scan_en), .Q (b_rptr[5]));
  SDFFQX1 \wptr_h_b_wptr_reg[5] (.CK (wclk), .D (n_86), .SI
       (b_wptr[4]), .SE (scan_en), .Q (b_wptr[5]));
  SDFFRHQX1 \sync_wptr_dout_reg[3] (.RN (rst), .CK (rclk), .D
       (g_wptr[3]), .SI (g_wptr_sync[2]), .SE (scan_en), .Q
       (g_wptr_sync[3]));
  SDFFRHQX1 \sync_rptr_dout_reg[3] (.RN (rst), .CK (wclk), .D
       (g_rptr[3]), .SI (g_rptr_sync[2]), .SE (scan_en), .Q
       (g_rptr_sync[3]));
  CLKINVX1 g1150(.A (n_94), .Y (n_93));
  INVX1 g1151(.A (n_92), .Y (n_91));
  OAI21X1 g1152__6783(.A0 (n_62), .A1 (n_76), .B0 (n_87), .Y (n_96));
  OAI21X1 g1153__3680(.A0 (n_61), .A1 (n_77), .B0 (n_88), .Y (n_95));
  OAI21X1 g1154__1617(.A0 (b_rptr[6]), .A1 (n_75), .B0 (n_90), .Y
       (n_94));
  AOI21X1 g1155__2802(.A0 (b_wptr[6]), .A1 (n_72), .B0 (n_89), .Y
       (n_92));
  NAND2XL g1156__1705(.A (b_rptr[6]), .B (n_75), .Y (n_90));
  SDFFQXL \wptr_h_g_wptr_reg[3] (.CK (wclk), .D (n_80), .SI
       (g_wptr[2]), .SE (scan_en), .Q (g_wptr[3]));
  SDFFQXL \rptr_h_g_rptr_reg[3] (.CK (rclk), .D (n_81), .SI
       (g_rptr[2]), .SE (scan_en), .Q (g_rptr[3]));
  NOR2XL g1159__5122(.A (b_wptr[6]), .B (n_72), .Y (n_89));
  NAND2XL g1161__8246(.A (n_61), .B (n_77), .Y (n_88));
  NAND2XL g1162__7098(.A (n_62), .B (n_76), .Y (n_87));
  NOR2XL g1163__6131(.A (n_77), .B (n_7), .Y (n_86));
  AOI21XL g1164__1881(.A0 (g_rptr_sync[2]), .A1 (n_64), .B0 (n_83), .Y
       (n_85));
  AOI21XL g1165__5115(.A0 (g_wptr_sync[2]), .A1 (n_63), .B0 (n_82), .Y
       (n_84));
  NOR2XL g1167__7482(.A (g_rptr_sync[2]), .B (n_64), .Y (n_83));
  NOR2XL g1168__4733(.A (g_wptr_sync[2]), .B (n_63), .Y (n_82));
  AND2XL g1169__6161(.A (n_9), .B (n_79), .Y (n_81));
  AND2XL g1170__9315(.A (n_78), .B (rst), .Y (n_80));
  SDFFQX1 \rptr_h_b_rptr_reg[4] (.CK (rclk), .D (n_71), .SI
       (b_rptr[3]), .SE (scan_en), .Q (b_rptr[4]));
  SDFFQX1 \wptr_h_b_wptr_reg[4] (.CK (wclk), .D (n_3), .SI (b_wptr[3]),
       .SE (scan_en), .Q (b_wptr[4]));
  SDFFRHQX1 \sync_rptr_dout_reg[2] (.RN (rst), .CK (wclk), .D
       (g_rptr[2]), .SI (g_rptr_sync[1]), .SE (scan_en), .Q
       (g_rptr_sync[2]));
  SDFFRHQX1 \sync_wptr_dout_reg[2] (.RN (rst), .CK (rclk), .D
       (g_wptr[2]), .SI (g_wptr_sync[1]), .SE (scan_en), .Q
       (g_wptr_sync[2]));
  OAI21X1 g1175__9945(.A0 (n_47), .A1 (n_62), .B0 (n_69), .Y (n_79));
  OAI21X1 g1176__2883(.A0 (n_46), .A1 (n_61), .B0 (n_70), .Y (n_78));
  AOI21X1 g1177__2346(.A0 (b_wptr[5]), .A1 (n_57), .B0 (n_73), .Y
       (n_77));
  OAI21X1 g1178__1666(.A0 (b_rptr[5]), .A1 (n_60), .B0 (n_74), .Y
       (n_76));
  NAND2XL g1179__7410(.A (b_rptr[5]), .B (n_60), .Y (n_74));
  SDFFQX1 \wptr_h_g_wptr_reg[2] (.CK (wclk), .D (n_65), .SI
       (g_wptr[1]), .SE (scan_en), .Q (g_wptr[2]));
  SDFFQXL \rptr_h_g_rptr_reg[2] (.CK (rclk), .D (n_66), .SI
       (g_rptr[1]), .SE (scan_en), .Q (g_rptr[2]));
  NOR2XL g1182__6417(.A (b_wptr[5]), .B (n_57), .Y (n_73));
  NAND2BX1 g1183__5477(.AN (n_60), .B (b_rptr[5]), .Y (n_75));
  NOR2XL g1185__2398(.A (n_5), .B (n_62), .Y (n_71));
  NAND2XL g1186__5107(.A (n_46), .B (n_61), .Y (n_70));
  NAND2XL g1187__6260(.A (n_47), .B (n_62), .Y (n_69));
  NAND2BX1 g1188__4319(.AN (n_57), .B (b_wptr[5]), .Y (n_72));
  NOR2XL g1190__8428(.A (g_wptr_sync[1]), .B (n_49), .Y (n_68));
  NOR2XL g1191__5526(.A (g_rptr_sync[1]), .B (n_48), .Y (n_67));
  AND2XL g1192__6783(.A (n_9), .B (n_63), .Y (n_66));
  AND2XL g1193__3680(.A (n_64), .B (rst), .Y (n_65));
  SDFFQX1 \wptr_h_b_wptr_reg[3] (.CK (wclk), .D (n_56), .SI
       (b_wptr[2]), .SE (scan_en), .Q (b_wptr[3]));
  SDFFQX1 \rptr_h_b_rptr_reg[3] (.CK (rclk), .D (n_2), .SI (b_rptr[2]),
       .SE (scan_en), .Q (b_rptr[3]));
  SDFFRHQX1 \sync_rptr_dout_reg[1] (.RN (rst), .CK (wclk), .D
       (g_rptr[1]), .SI (g_rptr_sync[0]), .SE (scan_en), .Q
       (g_rptr_sync[1]));
  SDFFRHQX1 \sync_wptr_dout_reg[1] (.RN (rst), .CK (rclk), .D
       (g_wptr[1]), .SI (g_wptr_sync[0]), .SE (scan_en), .Q
       (g_wptr_sync[1]));
  OAI21X1 g1198__1617(.A0 (n_34), .A1 (n_46), .B0 (n_54), .Y (n_64));
  OAI21X1 g1199__2802(.A0 (n_33), .A1 (n_47), .B0 (n_55), .Y (n_63));
  AOI21X1 g1200__1705(.A0 (b_rptr[4]), .A1 (n_44), .B0 (n_59), .Y
       (n_62));
  OAI21X1 g1201__5122(.A0 (b_wptr[4]), .A1 (n_45), .B0 (n_58), .Y
       (n_61));
  NOR2XL g1202__8246(.A (b_rptr[4]), .B (n_44), .Y (n_59));
  SDFFQX1 \wptr_h_g_wptr_reg[1] (.CK (wclk), .D (n_50), .SI
       (g_wptr[0]), .SE (scan_en), .Q (g_wptr[1]));
  SDFFQXL \rptr_h_g_rptr_reg[1] (.CK (rclk), .D (n_51), .SI
       (g_rptr[0]), .SE (scan_en), .Q (g_rptr[1]));
  NAND2XL g1205__7098(.A (b_wptr[4]), .B (n_45), .Y (n_58));
  NAND2BX1 g1206__6131(.AN (n_44), .B (b_rptr[4]), .Y (n_60));
  NOR2XL g1208__1881(.A (n_46), .B (n_7), .Y (n_56));
  NAND2XL g1209__5115(.A (n_33), .B (n_47), .Y (n_55));
  NAND2XL g1210__7482(.A (n_34), .B (n_46), .Y (n_54));
  NAND2BX1 g1211__4733(.AN (n_45), .B (b_wptr[4]), .Y (n_57));
  NAND2XL g1213__6161(.A (g_wptr_sync[0]), .B (n_36), .Y (n_53));
  NAND2XL g1214__9315(.A (g_rptr_sync[0]), .B (n_35), .Y (n_52));
  NOR2XL g1215__9945(.A (n_7), .B (n_49), .Y (n_51));
  NOR2XL g1216__2883(.A (n_48), .B (n_5), .Y (n_50));
  SDFFQX1 \wptr_h_b_wptr_reg[2] (.CK (wclk), .D (n_1), .SI (b_wptr[1]),
       .SE (scan_en), .Q (b_wptr[2]));
  SDFFQX1 \rptr_h_b_rptr_reg[2] (.CK (rclk), .D (n_42), .SI
       (b_rptr[1]), .SE (scan_en), .Q (b_rptr[2]));
  SDFFRHQX1 \sync_rptr_dout_reg[0] (.RN (rst), .CK (wclk), .D
       (g_rptr[0]), .SI (DFT_sdi_1), .SE (scan_en), .Q
       (g_rptr_sync[0]));
  SDFFRHQX1 \sync_wptr_dout_reg[0] (.RN (rst), .CK (rclk), .D
       (g_wptr[0]), .SI (g_rptr[6]), .SE (scan_en), .Q
       (g_wptr_sync[0]));
  AOI21X1 g1221__2346(.A0 (n_25), .A1 (n_33), .B0 (n_39), .Y (n_49));
  AOI21X1 g1222__1666(.A0 (n_24), .A1 (n_34), .B0 (n_40), .Y (n_48));
  OAI21X1 g1223__7410(.A0 (b_rptr[3]), .A1 (n_31), .B0 (n_43), .Y
       (n_47));
  AOI21X1 g1224__6417(.A0 (b_wptr[3]), .A1 (n_32), .B0 (n_41), .Y
       (n_46));
  NAND2XL g1225__5477(.A (b_rptr[3]), .B (n_31), .Y (n_43));
  SDFFQX1 \wptr_h_g_wptr_reg[0] (.CK (wclk), .D (n_37), .SI (full), .SE
       (scan_en), .Q (g_wptr[0]));
  SDFFQX1 \rptr_h_g_rptr_reg[0] (.CK (rclk), .D (n_38), .SI (empty),
       .SE (scan_en), .Q (g_rptr[0]));
  NAND2BX1 g1228__2398(.AN (n_32), .B (b_wptr[3]), .Y (n_45));
  NAND2BX1 g1229__5107(.AN (n_31), .B (b_rptr[3]), .Y (n_44));
  NOR2XL g1230__6260(.A (n_6), .B (n_33), .Y (n_42));
  NOR2XL g1232__4319(.A (b_wptr[3]), .B (n_32), .Y (n_41));
  NOR2XL g1233__8428(.A (n_24), .B (n_34), .Y (n_40));
  NOR2XL g1234__5526(.A (n_25), .B (n_33), .Y (n_39));
  NOR2XL g1236__6783(.A (n_7), .B (n_36), .Y (n_38));
  NOR2XL g1237__3680(.A (n_35), .B (n_7), .Y (n_37));
  SDFFQX1 \rptr_h_b_rptr_reg[1] (.CK (rclk), .D (n_0), .SI (b_rptr[0]),
       .SE (scan_en), .Q (b_rptr[1]));
  SDFFQX1 \wptr_h_b_wptr_reg[1] (.CK (wclk), .D (n_27), .SI
       (b_wptr[0]), .SE (scan_en), .Q (b_wptr[1]));
  AOI21X1 g1240__1617(.A0 (n_16), .A1 (n_25), .B0 (n_26), .Y (n_36));
  AOI21X1 g1241__2802(.A0 (n_17), .A1 (n_24), .B0 (n_28), .Y (n_35));
  OAI21X1 g1242__1705(.A0 (b_wptr[2]), .A1 (n_23), .B0 (n_29), .Y
       (n_34));
  AOI21X1 g1243__5122(.A0 (b_rptr[2]), .A1 (n_20), .B0 (n_30), .Y
       (n_33));
  NOR2XL g1244__8246(.A (b_rptr[2]), .B (n_20), .Y (n_30));
  NAND2XL g1245__7098(.A (b_wptr[2]), .B (n_23), .Y (n_29));
  NAND2BX1 g1246__6131(.AN (n_23), .B (b_wptr[2]), .Y (n_32));
  NAND2BX1 g1247__1881(.AN (n_20), .B (b_rptr[2]), .Y (n_31));
  NOR2XL g1248__5115(.A (n_17), .B (n_24), .Y (n_28));
  NOR2XL g1249__7482(.A (n_24), .B (n_7), .Y (n_27));
  NOR2XL g1251__4733(.A (n_16), .B (n_25), .Y (n_26));
  SDFFQX1 \rptr_h_b_rptr_reg[0] (.CK (rclk), .D (n_19), .SI (scan_in),
       .SE (scan_en), .Q (b_rptr[0]));
  SDFFQX1 \wptr_h_b_wptr_reg[0] (.CK (wclk), .D (n_18), .SI
       (g_rptr_sync[6]), .SE (scan_en), .Q (b_wptr[0]));
  OAI21X1 g1255__6161(.A0 (b_rptr[1]), .A1 (n_13), .B0 (n_22), .Y
       (n_25));
  AOI21X1 g1256__9315(.A0 (b_wptr[1]), .A1 (n_12), .B0 (n_21), .Y
       (n_24));
  NAND2XL g1257__9945(.A (b_rptr[1]), .B (n_13), .Y (n_22));
  NOR2XL g1258__2883(.A (b_wptr[1]), .B (n_12), .Y (n_21));
  NAND2BX1 g1259__2346(.AN (n_12), .B (b_wptr[1]), .Y (n_23));
  NOR2XL g1260__1666(.A (n_6), .B (n_16), .Y (n_19));
  AND2XL g1261__7410(.A (n_17), .B (rst), .Y (n_18));
  NAND2BX1 g1262__6417(.AN (n_13), .B (b_rptr[1]), .Y (n_20));
  OAI21X1 g1263__5477(.A0 (b_wptr[0]), .A1 (n_10), .B0 (n_14), .Y
       (n_17));
  AOI21X1 g1264__2398(.A0 (b_rptr[0]), .A1 (n_11), .B0 (n_15), .Y
       (n_16));
  NOR2XL g1265__5107(.A (b_rptr[0]), .B (n_11), .Y (n_15));
  NAND2XL g1266__6260(.A (b_wptr[0]), .B (n_10), .Y (n_14));
  NAND2BX1 g1267__4319(.AN (n_11), .B (b_rptr[0]), .Y (n_13));
  NAND2BX1 g1268__8428(.AN (n_10), .B (b_wptr[0]), .Y (n_12));
  SDFFRHQX1 \sync_rptr_dout_reg[6] (.RN (rst), .CK (wclk), .D
       (g_rptr[6]), .SI (g_rptr_sync[5]), .SE (scan_en), .Q
       (g_rptr_sync[6]));
  SDFFRHQX1 \sync_wptr_dout_reg[6] (.RN (rst), .CK (rclk), .D
       (DFT_sdo_1), .SI (g_wptr_sync[5]), .SE (scan_en), .Q (scan_out));
  NAND2BX1 g1271__5526(.AN (empty), .B (r_en), .Y (n_11));
  NAND2BX1 g1272__6783(.AN (full), .B (w_en), .Y (n_10));
  INVXL g1275(.A (n_5), .Y (n_9));
  CLKINVX1 drc_bufs1277(.A (rst), .Y (n_5));
  CLKINVX1 drc_bufs1278(.A (rst), .Y (n_7));
  NOR2BXL g2__3680(.AN (n_76), .B (n_6), .Y (n_4));
  NOR2BXL g1283__1617(.AN (n_61), .B (n_7), .Y (n_3));
  NOR2BXL g1284__2802(.AN (n_47), .B (n_7), .Y (n_2));
  NOR2BXL g1285__1705(.AN (n_34), .B (n_6), .Y (n_1));
  NOR2BXL g1286__5122(.AN (n_25), .B (n_7), .Y (n_0));
endmodule

