
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Mar 15 2026 21:24:27 IST (Mar 15 2026 15:54:27 UTC)

// Verification Directory fv/asynchronous_fifo 

module asynchronous_fifo(wclk, rclk, rst, w_en, r_en, data_in,
     data_out, full, empty, scan_en, scan_in, scan_out, DFT_sdi_1,
     DFT_sdo_1);
  input wclk, rclk, rst, w_en, r_en, scan_en, scan_in, DFT_sdi_1;
  input [7:0] data_in;
  output [7:0] data_out;
  output full, empty, scan_out, DFT_sdo_1;
  wire wclk, rclk, rst, w_en, r_en, scan_en, scan_in, DFT_sdi_1;
  wire [7:0] data_in;
  wire [7:0] data_out;
  wire full, empty, scan_out, DFT_sdo_1;
  wire [6:0] b_wptr;
  wire [6:0] b_rptr;
  wire [6:0] g_rptr_sync;
  wire [6:0] g_wptr_sync;
  wire [6:0] g_rptr;
  wire [6:0] g_wptr;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  FIFO_Memory_DEPTH64_DATA_WIDTH8_PTR_WIDTH6 fifom(.wclk (wclk), .w_en
       (w_en), .rclk (rclk), .r_en (r_en), .b_wptr (b_wptr), .b_rptr
       (b_rptr), .din (data_in), .full (full), .empty (empty), .dout
       (data_out));
  CLKINVX1 g6618(.A (rst), .Y (n_7));
  SDFFQX1 wptr_h_full_reg(.CK (wclk), .D (n_120), .SI (b_wptr[6]), .SE
       (scan_en), .Q (full));
  NOR2XL g7769__2398(.A (n_119), .B (n_6), .Y (n_120));
  NAND4XL g7770__5107(.A (n_57), .B (n_111), .C (n_113), .D (n_117), .Y
       (n_119));
  SDFFQX1 rptr_h_empty_reg(.CK (rclk), .D (n_118), .SI (b_rptr[6]), .SE
       (scan_en), .Q (empty));
  NOR2XL g7772__6260(.A (n_6), .B (n_115), .Y (n_118));
  AOI211X1 g7773__4319(.A0 (g_rptr_sync[1]), .A1 (n_49), .B0 (n_84),
       .C0 (n_116), .Y (n_117));
  OAI211X1 g7774__8428(.A0 (g_rptr_sync[0]), .A1 (n_32), .B0 (n_62),
       .C0 (n_114), .Y (n_116));
  NAND4XL g7775__5526(.A (n_90), .B (n_105), .C (n_104), .D (n_109), .Y
       (n_115));
  NOR2XL g7776__6783(.A (n_102), .B (n_110), .Y (n_114));
  OAI21XL g7777__3680(.A0 (g_rptr_sync[5]), .A1 (n_74), .B0 (n_112), .Y
       (n_113));
  NAND2XL g7778__1617(.A (g_rptr_sync[5]), .B (n_74), .Y (n_112));
  OAI21XL g7779__2802(.A0 (g_rptr_sync[4]), .A1 (n_75), .B0 (n_108), .Y
       (n_111));
  AOI21XL g7780__1705(.A0 (g_rptr_sync[3]), .A1 (n_68), .B0 (n_107), .Y
       (n_110));
  AOI211X1 g7781__5122(.A0 (g_wptr_sync[1]), .A1 (n_50), .B0 (n_85),
       .C0 (n_106), .Y (n_109));
  NAND2XL g7782__8246(.A (g_rptr_sync[4]), .B (n_75), .Y (n_108));
  SDFFRHQX1 \sync_rptr_dout_reg[5] (.RN (rst), .CK (wclk), .D
       (g_rptr[5]), .SI (g_rptr_sync[4]), .SE (scan_en), .Q
       (g_rptr_sync[5]));
  NOR2XL g7784__7098(.A (g_rptr_sync[3]), .B (n_68), .Y (n_107));
  OAI211X1 g7785__6131(.A0 (g_wptr_sync[0]), .A1 (n_33), .B0 (n_61),
       .C0 (n_103), .Y (n_106));
  SDFFQX1 \rptr_h_g_rptr_reg[5] (.CK (rclk), .D (n_98), .SI
       (g_rptr[4]), .SE (scan_en), .Q (g_rptr[5]));
  SDFFRHQX1 \sync_rptr_dout_reg[4] (.RN (rst), .CK (wclk), .D
       (g_rptr[4]), .SI (g_rptr_sync[3]), .SE (scan_en), .Q
       (g_rptr_sync[4]));
  SDFFRHQX1 \sync_rptr_dout_reg[3] (.RN (rst), .CK (wclk), .D
       (g_rptr[3]), .SI (g_rptr_sync[2]), .SE (scan_en), .Q
       (g_rptr_sync[3]));
  OAI21XL g7789__1881(.A0 (g_wptr_sync[4]), .A1 (n_89), .B0 (n_100), .Y
       (n_105));
  OAI21XL g7790__5115(.A0 (g_wptr_sync[5]), .A1 (n_95), .B0 (n_101), .Y
       (n_104));
  NOR2XL g7791__7482(.A (n_99), .B (n_96), .Y (n_103));
  AOI21XL g7792__4733(.A0 (g_rptr_sync[2]), .A1 (n_69), .B0 (n_97), .Y
       (n_102));
  NAND2XL g7793__6161(.A (g_wptr_sync[5]), .B (n_95), .Y (n_101));
  SDFFQXL \rptr_h_g_rptr_reg[4] (.CK (rclk), .D (n_91), .SI
       (g_rptr[3]), .SE (scan_en), .Q (g_rptr[4]));
  SDFFQX1 \rptr_h_g_rptr_reg[3] (.CK (rclk), .D (n_92), .SI
       (g_rptr[2]), .SE (scan_en), .Q (g_rptr[3]));
  NAND2XL g7796__9315(.A (g_wptr_sync[4]), .B (n_89), .Y (n_100));
  AOI21XL g7797__9945(.A0 (g_wptr_sync[2]), .A1 (n_73), .B0 (n_93), .Y
       (n_99));
  AND2XL g7798__2883(.A (rst), .B (n_95), .Y (n_98));
  NOR2XL g7799__2346(.A (g_rptr_sync[2]), .B (n_69), .Y (n_97));
  AOI21XL g7800__1666(.A0 (g_wptr_sync[3]), .A1 (n_88), .B0 (n_94), .Y
       (n_96));
  SDFFQX1 \rptr_h_b_rptr_reg[6] (.CK (rclk), .D (n_4), .SI (b_rptr[5]),
       .SE (scan_en), .Q (b_rptr[6]));
  SDFFQX1 \rptr_h_g_rptr_reg[6] (.CK (rclk), .D (n_4), .SI (g_rptr[5]),
       .SE (scan_en), .Q (g_rptr[6]));
  SDFFRHQX1 \sync_rptr_dout_reg[2] (.RN (rst), .CK (wclk), .D
       (g_rptr[2]), .SI (g_rptr_sync[1]), .SE (scan_en), .Q
       (g_rptr_sync[2]));
  SDFFRHQX1 \sync_wptr_dout_reg[4] (.RN (rst), .CK (rclk), .D
       (g_wptr[4]), .SI (g_wptr_sync[3]), .SE (scan_en), .Q
       (g_wptr_sync[4]));
  SDFFRHQX1 \sync_wptr_dout_reg[5] (.RN (rst), .CK (rclk), .D
       (g_wptr[5]), .SI (g_wptr_sync[4]), .SE (scan_en), .Q
       (g_wptr_sync[5]));
  NOR2XL g7806__7410(.A (g_wptr_sync[3]), .B (n_88), .Y (n_94));
  NOR2XL g7807__6417(.A (g_wptr_sync[2]), .B (n_73), .Y (n_93));
  AND2XL g7808__5477(.A (rst), .B (n_88), .Y (n_92));
  AND2XL g7809__2398(.A (rst), .B (n_89), .Y (n_91));
  OAI21XL g7810__5107(.A0 (DFT_sdo_1), .A1 (n_83), .B0 (n_87), .Y
       (n_90));
  OAI21X1 g7811__6260(.A0 (n_59), .A1 (n_83), .B0 (n_86), .Y (n_95));
  SDFFQX1 \rptr_h_b_rptr_reg[4] (.CK (rclk), .D (n_81), .SI
       (b_rptr[3]), .SE (scan_en), .Q (b_rptr[4]));
  SDFFQXL \wptr_h_g_wptr_reg[4] (.CK (wclk), .D (n_78), .SI
       (g_wptr[3]), .SE (scan_en), .Q (g_wptr[4]));
  SDFFQXL \rptr_h_g_rptr_reg[2] (.CK (rclk), .D (n_80), .SI
       (g_rptr[1]), .SE (scan_en), .Q (g_rptr[2]));
  SDFFRHQX1 \sync_wptr_dout_reg[3] (.RN (rst), .CK (rclk), .D
       (g_wptr[3]), .SI (g_wptr_sync[2]), .SE (scan_en), .Q
       (g_wptr_sync[3]));
  SDFFRHQX1 \sync_wptr_dout_reg[2] (.RN (rst), .CK (rclk), .D
       (g_wptr[2]), .SI (g_wptr_sync[1]), .SE (scan_en), .Q
       (g_wptr_sync[2]));
  SDFFQXL \wptr_h_g_wptr_reg[5] (.CK (wclk), .D (n_79), .SI
       (g_wptr[4]), .SE (scan_en), .Q (g_wptr[5]));
  NAND2XL g7818__4319(.A (DFT_sdo_1), .B (n_83), .Y (n_87));
  NAND2XL g7819__8428(.A (n_59), .B (n_83), .Y (n_86));
  CLKXOR2X1 g7821__5526(.A (n_72), .B (n_59), .Y (n_89));
  OAI21X1 g7822__6783(.A0 (n_64), .A1 (n_72), .B0 (n_82), .Y (n_88));
  SDFFQXL \wptr_h_g_wptr_reg[3] (.CK (wclk), .D (n_70), .SI
       (g_wptr[2]), .SE (scan_en), .Q (g_wptr[3]));
  SDFFQX1 \wptr_h_g_wptr_reg[2] (.CK (wclk), .D (n_71), .SI
       (g_wptr[1]), .SE (scan_en), .Q (g_wptr[2]));
  SDFFQX1 \rptr_h_b_rptr_reg[5] (.CK (rclk), .D (n_76), .SI
       (b_rptr[4]), .SE (scan_en), .Q (b_rptr[5]));
  NOR2XL g7826__3680(.A (g_wptr_sync[1]), .B (n_50), .Y (n_85));
  NOR2XL g7827__1617(.A (g_rptr_sync[1]), .B (n_49), .Y (n_84));
  NAND2XL g7829__2802(.A (n_64), .B (n_72), .Y (n_82));
  NOR2XL g7830__1705(.A (n_5), .B (n_72), .Y (n_81));
  AND2XL g7831__5122(.A (rst), .B (n_73), .Y (n_80));
  NOR2XL g7832__8246(.A (n_74), .B (n_7), .Y (n_79));
  AND2XL g7833__7098(.A (n_75), .B (rst), .Y (n_78));
  OAI21X1 g7834__6131(.A0 (b_rptr[6]), .A1 (n_52), .B0 (n_77), .Y
       (n_83));
  NAND2XL g7835__1881(.A (b_rptr[6]), .B (n_52), .Y (n_77));
  SDFFQX1 \rptr_h_b_rptr_reg[3] (.CK (rclk), .D (n_3), .SI (b_rptr[2]),
       .SE (scan_en), .Q (b_rptr[3]));
  SDFFQX1 \wptr_h_b_wptr_reg[5] (.CK (wclk), .D (n_65), .SI
       (b_wptr[4]), .SE (scan_en), .Q (b_wptr[5]));
  NOR2XL g7838__5115(.A (n_5), .B (n_59), .Y (n_76));
  SDFFRHQX1 \sync_rptr_dout_reg[1] (.RN (rst), .CK (wclk), .D
       (g_rptr[1]), .SI (g_rptr_sync[0]), .SE (scan_en), .Q
       (g_rptr_sync[1]));
  SDFFRHQX1 \sync_wptr_dout_reg[1] (.RN (rst), .CK (rclk), .D
       (g_wptr[1]), .SI (g_wptr_sync[0]), .SE (scan_en), .Q
       (g_wptr_sync[1]));
  AND2XL g7841__7482(.A (n_69), .B (rst), .Y (n_71));
  AND2XL g7842__4733(.A (n_68), .B (rst), .Y (n_70));
  OAI21X1 g7843__6161(.A0 (n_37), .A1 (n_58), .B0 (n_66), .Y (n_75));
  OAI21X1 g7844__9315(.A0 (n_58), .A1 (n_43), .B0 (n_67), .Y (n_74));
  XNOR2X1 g7845__9945(.A (n_31), .B (n_64), .Y (n_73));
  OAI21X1 g7846__2883(.A0 (b_rptr[4]), .A1 (n_63), .B0 (n_44), .Y
       (n_72));
  SDFFQXL \wptr_h_g_wptr_reg[1] (.CK (wclk), .D (n_54), .SI
       (g_wptr[0]), .SE (scan_en), .Q (g_wptr[1]));
  SDFFQXL \rptr_h_g_rptr_reg[1] (.CK (rclk), .D (n_53), .SI
       (g_rptr[0]), .SE (scan_en), .Q (g_rptr[1]));
  SDFFQX1 \wptr_h_b_wptr_reg[3] (.CK (wclk), .D (n_55), .SI
       (b_wptr[2]), .SE (scan_en), .Q (b_wptr[3]));
  NAND2XL g7851__2346(.A (n_58), .B (n_43), .Y (n_67));
  NAND2XL g7852__1666(.A (n_37), .B (n_58), .Y (n_66));
  NOR2XL g7853__7410(.A (n_58), .B (n_5), .Y (n_65));
  OAI21X1 g7854__6417(.A0 (n_41), .A1 (n_48), .B0 (n_60), .Y (n_69));
  OAI21X1 g7855__5477(.A0 (n_48), .A1 (n_37), .B0 (n_56), .Y (n_68));
  ADDHX1 g7857__2398(.A (b_rptr[3]), .B (n_30), .CO (n_63), .S (n_64));
  SDFFQX1 \wptr_h_b_wptr_reg[6] (.CK (wclk), .D (n_51), .SI
       (b_wptr[5]), .SE (scan_en), .Q (b_wptr[6]));
  SDFFQX1 \wptr_h_g_wptr_reg[6] (.CK (wclk), .D (n_51), .SI
       (g_wptr[5]), .SE (scan_en), .Q (scan_out));
  SDFFQX1 \wptr_h_b_wptr_reg[4] (.CK (wclk), .D (n_2), .SI (b_wptr[3]),
       .SE (scan_en), .Q (b_wptr[4]));
  NAND2XL g7861__5107(.A (g_rptr_sync[0]), .B (n_32), .Y (n_62));
  NAND2XL g7862__6260(.A (g_wptr_sync[0]), .B (n_33), .Y (n_61));
  NAND2XL g7863__4319(.A (n_41), .B (n_48), .Y (n_60));
  OAI21XL g7864__8428(.A0 (g_rptr_sync[6]), .A1 (n_43), .B0 (n_47), .Y
       (n_57));
  NAND2XL g7865__5526(.A (n_48), .B (n_37), .Y (n_56));
  NOR2XL g7866__6783(.A (n_48), .B (n_5), .Y (n_55));
  NOR2XL g7867__3680(.A (n_49), .B (n_7), .Y (n_54));
  NOR2XL g7868__1617(.A (n_5), .B (n_50), .Y (n_53));
  OAI21X1 g7869__2802(.A0 (b_rptr[5]), .A1 (n_45), .B0 (n_52), .Y
       (n_59));
  OAI21X1 g7870__1705(.A0 (b_wptr[5]), .A1 (n_34), .B0 (n_0), .Y
       (n_58));
  SDFFQX1 \rptr_h_b_rptr_reg[2] (.CK (rclk), .D (n_42), .SI
       (b_rptr[1]), .SE (scan_en), .Q (b_rptr[2]));
  SDFFQX1 \wptr_h_b_wptr_reg[2] (.CK (wclk), .D (n_1), .SI (b_wptr[1]),
       .SE (scan_en), .Q (b_wptr[2]));
  SDFFRHQX1 \sync_rptr_dout_reg[0] (.RN (rst), .CK (wclk), .D
       (g_rptr[0]), .SI (scan_in), .SE (scan_en), .Q (g_rptr_sync[0]));
  SDFFRHQX1 \sync_wptr_dout_reg[0] (.RN (rst), .CK (rclk), .D
       (g_wptr[0]), .SI (g_rptr[6]), .SE (scan_en), .Q
       (g_wptr_sync[0]));
  NAND2XL g7875__5122(.A (b_rptr[5]), .B (n_45), .Y (n_52));
  NAND2XL g7876__8246(.A (g_rptr_sync[6]), .B (n_43), .Y (n_47));
  NOR2XL g7878__7098(.A (n_43), .B (n_6), .Y (n_51));
  OAI21X1 g7879__6131(.A0 (n_22), .A1 (n_31), .B0 (n_46), .Y (n_50));
  CLKXOR2X1 g7880__1881(.A (n_23), .B (n_41), .Y (n_49));
  OAI21X1 g7881__5115(.A0 (b_wptr[3]), .A1 (n_40), .B0 (n_26), .Y
       (n_48));
  SDFFQXL \rptr_h_g_rptr_reg[0] (.CK (rclk), .D (n_38), .SI (empty),
       .SE (scan_en), .Q (g_rptr[0]));
  SDFFQXL \wptr_h_g_wptr_reg[0] (.CK (wclk), .D (n_36), .SI (full), .SE
       (scan_en), .Q (g_wptr[0]));
  NAND2XL g7885__7482(.A (n_22), .B (n_31), .Y (n_46));
  INVX1 g7886(.A (n_44), .Y (n_45));
  NOR2XL g7888__4733(.A (n_6), .B (n_31), .Y (n_42));
  NAND3X1 g7889__6161(.A (b_rptr[4]), .B (b_rptr[3]), .C (n_30), .Y
       (n_44));
  AOI21X1 g7890__9315(.A0 (b_wptr[6]), .A1 (n_0), .B0 (n_39), .Y
       (n_43));
  ADDHXL g7892__9945(.A (b_wptr[2]), .B (n_21), .CO (n_40), .S (n_41));
  NOR2XL g7893__2883(.A (b_wptr[6]), .B (n_0), .Y (n_39));
  NOR2XL g7894__2346(.A (n_6), .B (n_33), .Y (n_38));
  NOR2XL g7895__1666(.A (n_32), .B (n_7), .Y (n_36));
  OAI21X1 g7896__7410(.A0 (b_wptr[4]), .A1 (n_26), .B0 (n_35), .Y
       (n_37));
  NAND2XL g7897__6417(.A (b_wptr[4]), .B (n_26), .Y (n_35));
  SDFFQX1 \rptr_h_b_rptr_reg[1] (.CK (rclk), .D (n_24), .SI
       (b_rptr[0]), .SE (scan_en), .Q (b_rptr[1]));
  SDFFQX1 \wptr_h_b_wptr_reg[1] (.CK (wclk), .D (n_27), .SI
       (b_wptr[0]), .SE (scan_en), .Q (b_wptr[1]));
  NOR2BX1 g7900__5477(.AN (b_wptr[4]), .B (n_26), .Y (n_34));
  OAI21X1 g7901__2398(.A0 (n_15), .A1 (n_22), .B0 (n_28), .Y (n_33));
  OAI21X1 g7903__5107(.A0 (n_14), .A1 (n_23), .B0 (n_25), .Y (n_32));
  OAI21X1 g7904__6260(.A0 (b_rptr[2]), .A1 (n_18), .B0 (n_29), .Y
       (n_31));
  CLKINVX1 g7905(.A (n_29), .Y (n_30));
  NAND2XL g7906__4319(.A (n_15), .B (n_22), .Y (n_28));
  NOR2XL g7907__8428(.A (n_23), .B (n_7), .Y (n_27));
  NAND2XL g7908__5526(.A (b_rptr[2]), .B (n_18), .Y (n_29));
  NAND2XL g7910__6783(.A (n_14), .B (n_23), .Y (n_25));
  NOR2XL g7911__3680(.A (n_6), .B (n_22), .Y (n_24));
  NAND3X1 g7912__1617(.A (b_wptr[3]), .B (b_wptr[2]), .C (n_21), .Y
       (n_26));
  SDFFQX1 \rptr_h_b_rptr_reg[0] (.CK (rclk), .D (n_19), .SI
       (DFT_sdi_1), .SE (scan_en), .Q (b_rptr[0]));
  SDFFQX1 \wptr_h_b_wptr_reg[0] (.CK (wclk), .D (n_16), .SI
       (g_rptr_sync[6]), .SE (scan_en), .Q (b_wptr[0]));
  OAI21X1 g7915__2802(.A0 (b_wptr[1]), .A1 (n_12), .B0 (n_20), .Y
       (n_23));
  AOI21X1 g7916__1705(.A0 (b_rptr[1]), .A1 (n_11), .B0 (n_17), .Y
       (n_22));
  CLKINVX1 g7917(.A (n_20), .Y (n_21));
  NOR2XL g7918__5122(.A (n_6), .B (n_15), .Y (n_19));
  NAND2XL g7919__8246(.A (b_wptr[1]), .B (n_12), .Y (n_20));
  NOR2XL g7920__7098(.A (b_rptr[1]), .B (n_11), .Y (n_17));
  NOR2XL g7921__6131(.A (n_14), .B (n_7), .Y (n_16));
  NOR2BX1 g7922__1881(.AN (b_rptr[1]), .B (n_11), .Y (n_18));
  OAI21X1 g7923__5115(.A0 (b_rptr[0]), .A1 (n_10), .B0 (n_11), .Y
       (n_15));
  AOI21X1 g7924__7482(.A0 (b_wptr[0]), .A1 (n_9), .B0 (n_13), .Y
       (n_14));
  NOR2XL g7925__4733(.A (b_wptr[0]), .B (n_9), .Y (n_13));
  NOR2BX1 g7926__6161(.AN (b_wptr[0]), .B (n_9), .Y (n_12));
  NAND2XL g7927__9315(.A (b_rptr[0]), .B (n_10), .Y (n_11));
  SDFFRHQX1 \sync_rptr_dout_reg[6] (.RN (rst), .CK (wclk), .D
       (g_rptr[6]), .SI (g_rptr_sync[5]), .SE (scan_en), .Q
       (g_rptr_sync[6]));
  SDFFRHQX1 \sync_wptr_dout_reg[6] (.RN (rst), .CK (rclk), .D
       (scan_out), .SI (g_wptr_sync[5]), .SE (scan_en), .Q (DFT_sdo_1));
  NOR2BX1 g7930__9945(.AN (r_en), .B (empty), .Y (n_10));
  NAND2BX1 g7931__2883(.AN (full), .B (w_en), .Y (n_9));
  CLKINVX1 drc_bufs(.A (rst), .Y (n_6));
  CLKINVX1 drc_bufs7938(.A (rst), .Y (n_5));
  NOR2BXL g2__2346(.AN (n_83), .B (n_5), .Y (n_4));
  NOR2BXL g7944__1666(.AN (n_64), .B (n_5), .Y (n_3));
  NOR2BXL g7945__7410(.AN (n_37), .B (n_7), .Y (n_2));
  NOR2BXL g7946__6417(.AN (n_41), .B (n_7), .Y (n_1));
  NAND3BX1 g7947__5477(.AN (n_26), .B (b_wptr[5]), .C (b_wptr[4]), .Y
       (n_0));
endmodule

