
//input ports
add mapped point wclk wclk -type PI PI
add mapped point rclk rclk -type PI PI
add mapped point rst rst -type PI PI
add mapped point w_en w_en -type PI PI
add mapped point r_en r_en -type PI PI
add mapped point data_in[7] data_in[7] -type PI PI
add mapped point data_in[6] data_in[6] -type PI PI
add mapped point data_in[5] data_in[5] -type PI PI
add mapped point data_in[4] data_in[4] -type PI PI
add mapped point data_in[3] data_in[3] -type PI PI
add mapped point data_in[2] data_in[2] -type PI PI
add mapped point data_in[1] data_in[1] -type PI PI
add mapped point data_in[0] data_in[0] -type PI PI

//output ports
add mapped point data_out[7] data_out[7] -type PO PO
add mapped point data_out[6] data_out[6] -type PO PO
add mapped point data_out[5] data_out[5] -type PO PO
add mapped point data_out[4] data_out[4] -type PO PO
add mapped point data_out[3] data_out[3] -type PO PO
add mapped point data_out[2] data_out[2] -type PO PO
add mapped point data_out[1] data_out[1] -type PO PO
add mapped point data_out[0] data_out[0] -type PO PO
add mapped point full full -type PO PO
add mapped point empty empty -type PO PO

//inout ports




//Sequential Pins
add mapped point rptr_h/empty/q rptr_h_empty_reg/Q  -type DFF DFF
add mapped point wptr_h/full/q wptr_h_full_reg/Q  -type DFF DFF
add mapped point sync_wptr/dout[5]/q sync_wptr_dout_reg[5]/Q  -type DFF DFF
add mapped point sync_wptr/dout[4]/q sync_wptr_dout_reg[4]/Q  -type DFF DFF
add mapped point sync_rptr/dout[5]/q sync_rptr_dout_reg[5]/Q  -type DFF DFF
add mapped point sync_rptr/dout[4]/q sync_rptr_dout_reg[4]/Q  -type DFF DFF
add mapped point sync_wptr/dout[3]/q sync_wptr_dout_reg[3]/Q  -type DFF DFF
add mapped point fifom/dout[0]/q fifom_dout_reg[0]/Q  -type DFF DFF
add mapped point fifom/dout[4]/q fifom_dout_reg[4]/Q  -type DFF DFF
add mapped point fifom/dout[1]/q fifom_dout_reg[1]/Q  -type DFF DFF
add mapped point fifom/dout[3]/q fifom_dout_reg[3]/Q  -type DFF DFF
add mapped point fifom/dout[6]/q fifom_dout_reg[6]/Q  -type DFF DFF
add mapped point fifom/dout[5]/q fifom_dout_reg[5]/Q  -type DFF DFF
add mapped point fifom/dout[2]/q fifom_dout_reg[2]/Q  -type DFF DFF
add mapped point fifom/dout[7]/q fifom_dout_reg[7]/Q  -type DFF DFF
add mapped point sync_rptr/dout[3]/q sync_rptr_dout_reg[3]/Q  -type DFF DFF
add mapped point sync_rptr/dout[2]/q sync_rptr_dout_reg[2]/Q  -type DFF DFF
add mapped point wptr_h/g_wptr[4]/q wptr_h_g_wptr_reg[4]/Q  -type DFF DFF
add mapped point wptr_h/g_wptr[5]/q wptr_h_g_wptr_reg[5]/Q  -type DFF DFF
add mapped point sync_wptr/dout[2]/q sync_wptr_dout_reg[2]/Q  -type DFF DFF
add mapped point rptr_h/g_rptr[4]/q rptr_h_g_rptr_reg[4]/Q  -type DFF DFF
add mapped point rptr_h/g_rptr[5]/q rptr_h_g_rptr_reg[5]/Q  -type DFF DFF
add mapped point wptr_h/g_wptr[3]/q wptr_h_g_wptr_reg[3]/Q  -type DFF DFF
add mapped point sync_wptr/dout[1]/q sync_wptr_dout_reg[1]/Q  -type DFF DFF
add mapped point rptr_h/g_rptr[3]/q rptr_h_g_rptr_reg[3]/Q  -type DFF DFF
add mapped point sync_rptr/dout[1]/q sync_rptr_dout_reg[1]/Q  -type DFF DFF
add mapped point rptr_h/g_rptr[2]/q rptr_h_g_rptr_reg[2]/Q  -type DFF DFF
add mapped point wptr_h/g_wptr[2]/q wptr_h_g_wptr_reg[2]/Q  -type DFF DFF
add mapped point wptr_h/b_wptr[6]/q wptr_h_b_wptr_reg[6]/Q  -type DFF DFF
add mapped point wptr_h/b_wptr[5]/q wptr_h_b_wptr_reg[5]/Q  -type DFF DFF
add mapped point rptr_h/b_rptr[5]/q rptr_h_b_rptr_reg[5]/Q  -type DFF DFF
add mapped point sync_wptr/dout[0]/q sync_wptr_dout_reg[0]/Q  -type DFF DFF
add mapped point sync_rptr/dout[0]/q sync_rptr_dout_reg[0]/Q  -type DFF DFF
add mapped point wptr_h/b_wptr[4]/q wptr_h_b_wptr_reg[4]/Q  -type DFF DFF
add mapped point wptr_h/g_wptr[1]/q wptr_h_g_wptr_reg[1]/Q  -type DFF DFF
add mapped point rptr_h/g_rptr[1]/q rptr_h_g_rptr_reg[1]/Q  -type DFF DFF
add mapped point rptr_h/b_rptr[3]/q rptr_h_b_rptr_reg[3]/Q  -type DFF DFF
add mapped point rptr_h/b_rptr[4]/q rptr_h_b_rptr_reg[4]/Q  -type DFF DFF
add mapped point fifom/fifo[61][5]/q fifom_fifo_reg[61][5]/Q  -type DFF DFF
add mapped point fifom/fifo[53][7]/q fifom_fifo_reg[53][7]/Q  -type DFF DFF
add mapped point fifom/fifo[37][0]/q fifom_fifo_reg[37][0]/Q  -type DFF DFF
add mapped point fifom/fifo[37][1]/q fifom_fifo_reg[37][1]/Q  -type DFF DFF
add mapped point fifom/fifo[37][3]/q fifom_fifo_reg[37][3]/Q  -type DFF DFF
add mapped point fifom/fifo[37][4]/q fifom_fifo_reg[37][4]/Q  -type DFF DFF
add mapped point fifom/fifo[37][5]/q fifom_fifo_reg[37][5]/Q  -type DFF DFF
add mapped point fifom/fifo[37][6]/q fifom_fifo_reg[37][6]/Q  -type DFF DFF
add mapped point wptr_h/b_wptr[3]/q wptr_h_b_wptr_reg[3]/Q  -type DFF DFF
add mapped point fifom/fifo[37][7]/q fifom_fifo_reg[37][7]/Q  -type DFF DFF
add mapped point fifom/fifo[49][0]/q fifom_fifo_reg[49][0]/Q  -type DFF DFF
add mapped point fifom/fifo[49][1]/q fifom_fifo_reg[49][1]/Q  -type DFF DFF
add mapped point fifom/fifo[49][2]/q fifom_fifo_reg[49][2]/Q  -type DFF DFF
add mapped point fifom/fifo[49][3]/q fifom_fifo_reg[49][3]/Q  -type DFF DFF
add mapped point fifom/fifo[49][4]/q fifom_fifo_reg[49][4]/Q  -type DFF DFF
add mapped point fifom/fifo[49][6]/q fifom_fifo_reg[49][6]/Q  -type DFF DFF
add mapped point fifom/fifo[49][5]/q fifom_fifo_reg[49][5]/Q  -type DFF DFF
add mapped point fifom/fifo[49][7]/q fifom_fifo_reg[49][7]/Q  -type DFF DFF
add mapped point fifom/fifo[53][0]/q fifom_fifo_reg[53][0]/Q  -type DFF DFF
add mapped point fifom/fifo[53][1]/q fifom_fifo_reg[53][1]/Q  -type DFF DFF
add mapped point fifom/fifo[53][2]/q fifom_fifo_reg[53][2]/Q  -type DFF DFF
add mapped point fifom/fifo[53][3]/q fifom_fifo_reg[53][3]/Q  -type DFF DFF
add mapped point fifom/fifo[53][4]/q fifom_fifo_reg[53][4]/Q  -type DFF DFF
add mapped point fifom/fifo[53][5]/q fifom_fifo_reg[53][5]/Q  -type DFF DFF
add mapped point fifom/fifo[53][6]/q fifom_fifo_reg[53][6]/Q  -type DFF DFF
add mapped point fifom/fifo[55][0]/q fifom_fifo_reg[55][0]/Q  -type DFF DFF
add mapped point fifom/fifo[55][1]/q fifom_fifo_reg[55][1]/Q  -type DFF DFF
add mapped point fifom/fifo[55][2]/q fifom_fifo_reg[55][2]/Q  -type DFF DFF
add mapped point fifom/fifo[55][3]/q fifom_fifo_reg[55][3]/Q  -type DFF DFF
add mapped point fifom/fifo[55][4]/q fifom_fifo_reg[55][4]/Q  -type DFF DFF
add mapped point fifom/fifo[55][5]/q fifom_fifo_reg[55][5]/Q  -type DFF DFF
add mapped point fifom/fifo[55][6]/q fifom_fifo_reg[55][6]/Q  -type DFF DFF
add mapped point fifom/fifo[55][7]/q fifom_fifo_reg[55][7]/Q  -type DFF DFF
add mapped point fifom/fifo[61][0]/q fifom_fifo_reg[61][0]/Q  -type DFF DFF
add mapped point fifom/fifo[61][1]/q fifom_fifo_reg[61][1]/Q  -type DFF DFF
add mapped point fifom/fifo[61][2]/q fifom_fifo_reg[61][2]/Q  -type DFF DFF
add mapped point fifom/fifo[61][3]/q fifom_fifo_reg[61][3]/Q  -type DFF DFF
add mapped point fifom/fifo[61][4]/q fifom_fifo_reg[61][4]/Q  -type DFF DFF
add mapped point fifom/fifo[61][6]/q fifom_fifo_reg[61][6]/Q  -type DFF DFF
add mapped point fifom/fifo[61][7]/q fifom_fifo_reg[61][7]/Q  -type DFF DFF
add mapped point fifom/fifo[37][2]/q fifom_fifo_reg[37][2]/Q  -type DFF DFF
add mapped point rptr_h/b_rptr[6]/q rptr_h_b_rptr_reg[6]/Q  -type DFF DFF
add mapped point fifom/fifo[45][3]/q fifom_fifo_reg[45][3]/Q  -type DFF DFF
add mapped point fifom/fifo[33][1]/q fifom_fifo_reg[33][1]/Q  -type DFF DFF
add mapped point fifom/fifo[57][2]/q fifom_fifo_reg[57][2]/Q  -type DFF DFF
add mapped point fifom/fifo[28][1]/q fifom_fifo_reg[28][1]/Q  -type DFF DFF
add mapped point fifom/fifo[16][3]/q fifom_fifo_reg[16][3]/Q  -type DFF DFF
add mapped point fifom/fifo[45][6]/q fifom_fifo_reg[45][6]/Q  -type DFF DFF
add mapped point fifom/fifo[51][6]/q fifom_fifo_reg[51][6]/Q  -type DFF DFF
add mapped point fifom/fifo[33][7]/q fifom_fifo_reg[33][7]/Q  -type DFF DFF
add mapped point fifom/fifo[41][6]/q fifom_fifo_reg[41][6]/Q  -type DFF DFF
add mapped point fifom/fifo[35][6]/q fifom_fifo_reg[35][6]/Q  -type DFF DFF
add mapped point fifom/fifo[45][2]/q fifom_fifo_reg[45][2]/Q  -type DFF DFF
add mapped point fifom/fifo[39][6]/q fifom_fifo_reg[39][6]/Q  -type DFF DFF
add mapped point fifom/fifo[4][4]/q fifom_fifo_reg[4][4]/Q  -type DFF DFF
add mapped point fifom/fifo[57][4]/q fifom_fifo_reg[57][4]/Q  -type DFF DFF
add mapped point fifom/fifo[59][6]/q fifom_fifo_reg[59][6]/Q  -type DFF DFF
add mapped point fifom/fifo[52][3]/q fifom_fifo_reg[52][3]/Q  -type DFF DFF
add mapped point fifom/fifo[27][5]/q fifom_fifo_reg[27][5]/Q  -type DFF DFF
add mapped point fifom/fifo[45][1]/q fifom_fifo_reg[45][1]/Q  -type DFF DFF
add mapped point fifom/fifo[33][0]/q fifom_fifo_reg[33][0]/Q  -type DFF DFF
add mapped point fifom/fifo[43][0]/q fifom_fifo_reg[43][0]/Q  -type DFF DFF
add mapped point fifom/fifo[43][1]/q fifom_fifo_reg[43][1]/Q  -type DFF DFF
add mapped point fifom/fifo[43][2]/q fifom_fifo_reg[43][2]/Q  -type DFF DFF
add mapped point fifom/fifo[43][3]/q fifom_fifo_reg[43][3]/Q  -type DFF DFF
add mapped point fifom/fifo[43][4]/q fifom_fifo_reg[43][4]/Q  -type DFF DFF
add mapped point fifom/fifo[43][5]/q fifom_fifo_reg[43][5]/Q  -type DFF DFF
add mapped point fifom/fifo[43][6]/q fifom_fifo_reg[43][6]/Q  -type DFF DFF
add mapped point fifom/fifo[43][7]/q fifom_fifo_reg[43][7]/Q  -type DFF DFF
add mapped point fifom/fifo[59][0]/q fifom_fifo_reg[59][0]/Q  -type DFF DFF
add mapped point fifom/fifo[59][1]/q fifom_fifo_reg[59][1]/Q  -type DFF DFF
add mapped point fifom/fifo[59][2]/q fifom_fifo_reg[59][2]/Q  -type DFF DFF
add mapped point fifom/fifo[59][3]/q fifom_fifo_reg[59][3]/Q  -type DFF DFF
add mapped point fifom/fifo[59][4]/q fifom_fifo_reg[59][4]/Q  -type DFF DFF
add mapped point fifom/fifo[59][5]/q fifom_fifo_reg[59][5]/Q  -type DFF DFF
add mapped point fifom/fifo[59][7]/q fifom_fifo_reg[59][7]/Q  -type DFF DFF
add mapped point fifom/fifo[35][0]/q fifom_fifo_reg[35][0]/Q  -type DFF DFF
add mapped point fifom/fifo[35][1]/q fifom_fifo_reg[35][1]/Q  -type DFF DFF
add mapped point fifom/fifo[35][2]/q fifom_fifo_reg[35][2]/Q  -type DFF DFF
add mapped point fifom/fifo[35][3]/q fifom_fifo_reg[35][3]/Q  -type DFF DFF
add mapped point fifom/fifo[35][4]/q fifom_fifo_reg[35][4]/Q  -type DFF DFF
add mapped point fifom/fifo[35][5]/q fifom_fifo_reg[35][5]/Q  -type DFF DFF
add mapped point fifom/fifo[35][7]/q fifom_fifo_reg[35][7]/Q  -type DFF DFF
add mapped point fifom/fifo[41][0]/q fifom_fifo_reg[41][0]/Q  -type DFF DFF
add mapped point fifom/fifo[41][1]/q fifom_fifo_reg[41][1]/Q  -type DFF DFF
add mapped point fifom/fifo[41][2]/q fifom_fifo_reg[41][2]/Q  -type DFF DFF
add mapped point fifom/fifo[41][3]/q fifom_fifo_reg[41][3]/Q  -type DFF DFF
add mapped point fifom/fifo[41][4]/q fifom_fifo_reg[41][4]/Q  -type DFF DFF
add mapped point fifom/fifo[41][5]/q fifom_fifo_reg[41][5]/Q  -type DFF DFF
add mapped point fifom/fifo[41][7]/q fifom_fifo_reg[41][7]/Q  -type DFF DFF
add mapped point fifom/fifo[47][0]/q fifom_fifo_reg[47][0]/Q  -type DFF DFF
add mapped point fifom/fifo[47][1]/q fifom_fifo_reg[47][1]/Q  -type DFF DFF
add mapped point fifom/fifo[47][2]/q fifom_fifo_reg[47][2]/Q  -type DFF DFF
add mapped point fifom/fifo[47][3]/q fifom_fifo_reg[47][3]/Q  -type DFF DFF
add mapped point fifom/fifo[47][4]/q fifom_fifo_reg[47][4]/Q  -type DFF DFF
add mapped point fifom/fifo[47][5]/q fifom_fifo_reg[47][5]/Q  -type DFF DFF
add mapped point fifom/fifo[47][6]/q fifom_fifo_reg[47][6]/Q  -type DFF DFF
add mapped point fifom/fifo[47][7]/q fifom_fifo_reg[47][7]/Q  -type DFF DFF
add mapped point fifom/fifo[11][1]/q fifom_fifo_reg[11][1]/Q  -type DFF DFF
add mapped point fifom/fifo[11][2]/q fifom_fifo_reg[11][2]/Q  -type DFF DFF
add mapped point fifom/fifo[11][3]/q fifom_fifo_reg[11][3]/Q  -type DFF DFF
add mapped point fifom/fifo[11][4]/q fifom_fifo_reg[11][4]/Q  -type DFF DFF
add mapped point fifom/fifo[11][5]/q fifom_fifo_reg[11][5]/Q  -type DFF DFF
add mapped point fifom/fifo[11][6]/q fifom_fifo_reg[11][6]/Q  -type DFF DFF
add mapped point fifom/fifo[11][0]/q fifom_fifo_reg[11][0]/Q  -type DFF DFF
add mapped point fifom/fifo[63][0]/q fifom_fifo_reg[63][0]/Q  -type DFF DFF
add mapped point fifom/fifo[63][1]/q fifom_fifo_reg[63][1]/Q  -type DFF DFF
add mapped point fifom/fifo[63][3]/q fifom_fifo_reg[63][3]/Q  -type DFF DFF
add mapped point fifom/fifo[63][4]/q fifom_fifo_reg[63][4]/Q  -type DFF DFF
add mapped point fifom/fifo[63][5]/q fifom_fifo_reg[63][5]/Q  -type DFF DFF
add mapped point fifom/fifo[63][6]/q fifom_fifo_reg[63][6]/Q  -type DFF DFF
add mapped point fifom/fifo[63][2]/q fifom_fifo_reg[63][2]/Q  -type DFF DFF
add mapped point fifom/fifo[39][0]/q fifom_fifo_reg[39][0]/Q  -type DFF DFF
add mapped point fifom/fifo[39][1]/q fifom_fifo_reg[39][1]/Q  -type DFF DFF
add mapped point fifom/fifo[39][2]/q fifom_fifo_reg[39][2]/Q  -type DFF DFF
add mapped point fifom/fifo[39][3]/q fifom_fifo_reg[39][3]/Q  -type DFF DFF
add mapped point fifom/fifo[39][4]/q fifom_fifo_reg[39][4]/Q  -type DFF DFF
add mapped point fifom/fifo[39][5]/q fifom_fifo_reg[39][5]/Q  -type DFF DFF
add mapped point fifom/fifo[39][7]/q fifom_fifo_reg[39][7]/Q  -type DFF DFF
add mapped point fifom/fifo[45][0]/q fifom_fifo_reg[45][0]/Q  -type DFF DFF
add mapped point wptr_h/b_wptr[2]/q wptr_h_b_wptr_reg[2]/Q  -type DFF DFF
add mapped point rptr_h/g_rptr[0]/q rptr_h_g_rptr_reg[0]/Q  -type DFF DFF
add mapped point wptr_h/g_wptr[0]/q wptr_h_g_wptr_reg[0]/Q  -type DFF DFF
add mapped point fifom/fifo[28][2]/q fifom_fifo_reg[28][2]/Q  -type DFF DFF
add mapped point fifom/fifo[51][1]/q fifom_fifo_reg[51][1]/Q  -type DFF DFF
add mapped point fifom/fifo[51][2]/q fifom_fifo_reg[51][2]/Q  -type DFF DFF
add mapped point fifom/fifo[51][3]/q fifom_fifo_reg[51][3]/Q  -type DFF DFF
add mapped point fifom/fifo[51][4]/q fifom_fifo_reg[51][4]/Q  -type DFF DFF
add mapped point fifom/fifo[51][5]/q fifom_fifo_reg[51][5]/Q  -type DFF DFF
add mapped point fifom/fifo[51][7]/q fifom_fifo_reg[51][7]/Q  -type DFF DFF
add mapped point fifom/fifo[57][0]/q fifom_fifo_reg[57][0]/Q  -type DFF DFF
add mapped point fifom/fifo[57][1]/q fifom_fifo_reg[57][1]/Q  -type DFF DFF
add mapped point fifom/fifo[57][6]/q fifom_fifo_reg[57][6]/Q  -type DFF DFF
add mapped point fifom/fifo[57][3]/q fifom_fifo_reg[57][3]/Q  -type DFF DFF
add mapped point fifom/fifo[57][7]/q fifom_fifo_reg[57][7]/Q  -type DFF DFF
add mapped point fifom/fifo[57][5]/q fifom_fifo_reg[57][5]/Q  -type DFF DFF
add mapped point fifom/fifo[16][5]/q fifom_fifo_reg[16][5]/Q  -type DFF DFF
add mapped point fifom/fifo[16][6]/q fifom_fifo_reg[16][6]/Q  -type DFF DFF
add mapped point fifom/fifo[16][7]/q fifom_fifo_reg[16][7]/Q  -type DFF DFF
add mapped point fifom/fifo[15][0]/q fifom_fifo_reg[15][0]/Q  -type DFF DFF
add mapped point fifom/fifo[20][0]/q fifom_fifo_reg[20][0]/Q  -type DFF DFF
add mapped point fifom/fifo[20][1]/q fifom_fifo_reg[20][1]/Q  -type DFF DFF
add mapped point fifom/fifo[20][2]/q fifom_fifo_reg[20][2]/Q  -type DFF DFF
add mapped point fifom/fifo[20][3]/q fifom_fifo_reg[20][3]/Q  -type DFF DFF
add mapped point fifom/fifo[20][4]/q fifom_fifo_reg[20][4]/Q  -type DFF DFF
add mapped point fifom/fifo[20][5]/q fifom_fifo_reg[20][5]/Q  -type DFF DFF
add mapped point fifom/fifo[20][6]/q fifom_fifo_reg[20][6]/Q  -type DFF DFF
add mapped point fifom/fifo[20][7]/q fifom_fifo_reg[20][7]/Q  -type DFF DFF
add mapped point fifom/fifo[22][0]/q fifom_fifo_reg[22][0]/Q  -type DFF DFF
add mapped point fifom/fifo[22][1]/q fifom_fifo_reg[22][1]/Q  -type DFF DFF
add mapped point fifom/fifo[22][2]/q fifom_fifo_reg[22][2]/Q  -type DFF DFF
add mapped point fifom/fifo[22][3]/q fifom_fifo_reg[22][3]/Q  -type DFF DFF
add mapped point fifom/fifo[22][4]/q fifom_fifo_reg[22][4]/Q  -type DFF DFF
add mapped point fifom/fifo[22][5]/q fifom_fifo_reg[22][5]/Q  -type DFF DFF
add mapped point fifom/fifo[22][6]/q fifom_fifo_reg[22][6]/Q  -type DFF DFF
add mapped point fifom/fifo[22][7]/q fifom_fifo_reg[22][7]/Q  -type DFF DFF
add mapped point fifom/fifo[27][0]/q fifom_fifo_reg[27][0]/Q  -type DFF DFF
add mapped point fifom/fifo[27][1]/q fifom_fifo_reg[27][1]/Q  -type DFF DFF
add mapped point fifom/fifo[27][2]/q fifom_fifo_reg[27][2]/Q  -type DFF DFF
add mapped point fifom/fifo[27][3]/q fifom_fifo_reg[27][3]/Q  -type DFF DFF
add mapped point fifom/fifo[27][4]/q fifom_fifo_reg[27][4]/Q  -type DFF DFF
add mapped point fifom/fifo[27][6]/q fifom_fifo_reg[27][6]/Q  -type DFF DFF
add mapped point fifom/fifo[27][7]/q fifom_fifo_reg[27][7]/Q  -type DFF DFF
add mapped point fifom/fifo[28][0]/q fifom_fifo_reg[28][0]/Q  -type DFF DFF
add mapped point fifom/fifo[51][0]/q fifom_fifo_reg[51][0]/Q  -type DFF DFF
add mapped point fifom/fifo[28][3]/q fifom_fifo_reg[28][3]/Q  -type DFF DFF
add mapped point fifom/fifo[28][5]/q fifom_fifo_reg[28][5]/Q  -type DFF DFF
add mapped point fifom/fifo[28][6]/q fifom_fifo_reg[28][6]/Q  -type DFF DFF
add mapped point fifom/fifo[28][7]/q fifom_fifo_reg[28][7]/Q  -type DFF DFF
add mapped point fifom/fifo[28][4]/q fifom_fifo_reg[28][4]/Q  -type DFF DFF
add mapped point fifom/fifo[52][0]/q fifom_fifo_reg[52][0]/Q  -type DFF DFF
add mapped point fifom/fifo[52][1]/q fifom_fifo_reg[52][1]/Q  -type DFF DFF
add mapped point fifom/fifo[52][2]/q fifom_fifo_reg[52][2]/Q  -type DFF DFF
add mapped point fifom/fifo[52][4]/q fifom_fifo_reg[52][4]/Q  -type DFF DFF
add mapped point fifom/fifo[52][5]/q fifom_fifo_reg[52][5]/Q  -type DFF DFF
add mapped point fifom/fifo[52][6]/q fifom_fifo_reg[52][6]/Q  -type DFF DFF
add mapped point fifom/fifo[52][7]/q fifom_fifo_reg[52][7]/Q  -type DFF DFF
add mapped point fifom/fifo[63][7]/q fifom_fifo_reg[63][7]/Q  -type DFF DFF
add mapped point fifom/fifo[4][0]/q fifom_fifo_reg[4][0]/Q  -type DFF DFF
add mapped point fifom/fifo[4][1]/q fifom_fifo_reg[4][1]/Q  -type DFF DFF
add mapped point fifom/fifo[4][2]/q fifom_fifo_reg[4][2]/Q  -type DFF DFF
add mapped point fifom/fifo[4][3]/q fifom_fifo_reg[4][3]/Q  -type DFF DFF
add mapped point fifom/fifo[4][5]/q fifom_fifo_reg[4][5]/Q  -type DFF DFF
add mapped point fifom/fifo[4][6]/q fifom_fifo_reg[4][6]/Q  -type DFF DFF
add mapped point fifom/fifo[4][7]/q fifom_fifo_reg[4][7]/Q  -type DFF DFF
add mapped point fifom/fifo[33][3]/q fifom_fifo_reg[33][3]/Q  -type DFF DFF
add mapped point fifom/fifo[33][4]/q fifom_fifo_reg[33][4]/Q  -type DFF DFF
add mapped point fifom/fifo[33][5]/q fifom_fifo_reg[33][5]/Q  -type DFF DFF
add mapped point fifom/fifo[33][2]/q fifom_fifo_reg[33][2]/Q  -type DFF DFF
add mapped point fifom/fifo[33][6]/q fifom_fifo_reg[33][6]/Q  -type DFF DFF
add mapped point fifom/fifo[15][1]/q fifom_fifo_reg[15][1]/Q  -type DFF DFF
add mapped point fifom/fifo[15][2]/q fifom_fifo_reg[15][2]/Q  -type DFF DFF
add mapped point fifom/fifo[15][3]/q fifom_fifo_reg[15][3]/Q  -type DFF DFF
add mapped point fifom/fifo[15][5]/q fifom_fifo_reg[15][5]/Q  -type DFF DFF
add mapped point fifom/fifo[15][6]/q fifom_fifo_reg[15][6]/Q  -type DFF DFF
add mapped point fifom/fifo[15][7]/q fifom_fifo_reg[15][7]/Q  -type DFF DFF
add mapped point fifom/fifo[16][0]/q fifom_fifo_reg[16][0]/Q  -type DFF DFF
add mapped point fifom/fifo[16][1]/q fifom_fifo_reg[16][1]/Q  -type DFF DFF
add mapped point fifom/fifo[16][2]/q fifom_fifo_reg[16][2]/Q  -type DFF DFF
add mapped point fifom/fifo[15][4]/q fifom_fifo_reg[15][4]/Q  -type DFF DFF
add mapped point fifom/fifo[16][4]/q fifom_fifo_reg[16][4]/Q  -type DFF DFF
add mapped point fifom/fifo[11][7]/q fifom_fifo_reg[11][7]/Q  -type DFF DFF
add mapped point fifom/fifo[45][7]/q fifom_fifo_reg[45][7]/Q  -type DFF DFF
add mapped point fifom/fifo[45][4]/q fifom_fifo_reg[45][4]/Q  -type DFF DFF
add mapped point fifom/fifo[45][5]/q fifom_fifo_reg[45][5]/Q  -type DFF DFF
add mapped point fifom/fifo[50][2]/q fifom_fifo_reg[50][2]/Q  -type DFF DFF
add mapped point fifom/fifo[13][6]/q fifom_fifo_reg[13][6]/Q  -type DFF DFF
add mapped point fifom/fifo[48][1]/q fifom_fifo_reg[48][1]/Q  -type DFF DFF
add mapped point fifom/fifo[6][2]/q fifom_fifo_reg[6][2]/Q  -type DFF DFF
add mapped point fifom/fifo[7][1]/q fifom_fifo_reg[7][1]/Q  -type DFF DFF
add mapped point fifom/fifo[23][5]/q fifom_fifo_reg[23][5]/Q  -type DFF DFF
add mapped point fifom/fifo[9][5]/q fifom_fifo_reg[9][5]/Q  -type DFF DFF
add mapped point fifom/fifo[3][1]/q fifom_fifo_reg[3][1]/Q  -type DFF DFF
add mapped point fifom/fifo[44][6]/q fifom_fifo_reg[44][6]/Q  -type DFF DFF
add mapped point fifom/fifo[14][2]/q fifom_fifo_reg[14][2]/Q  -type DFF DFF
add mapped point fifom/fifo[0][0]/q fifom_fifo_reg[0][0]/Q  -type DFF DFF
add mapped point fifom/fifo[21][6]/q fifom_fifo_reg[21][6]/Q  -type DFF DFF
add mapped point fifom/fifo[14][6]/q fifom_fifo_reg[14][6]/Q  -type DFF DFF
add mapped point fifom/fifo[6][6]/q fifom_fifo_reg[6][6]/Q  -type DFF DFF
add mapped point fifom/fifo[36][6]/q fifom_fifo_reg[36][6]/Q  -type DFF DFF
add mapped point fifom/fifo[31][5]/q fifom_fifo_reg[31][5]/Q  -type DFF DFF
add mapped point fifom/fifo[38][7]/q fifom_fifo_reg[38][7]/Q  -type DFF DFF
add mapped point fifom/fifo[31][1]/q fifom_fifo_reg[31][1]/Q  -type DFF DFF
add mapped point fifom/fifo[7][6]/q fifom_fifo_reg[7][6]/Q  -type DFF DFF
add mapped point fifom/fifo[29][2]/q fifom_fifo_reg[29][2]/Q  -type DFF DFF
add mapped point fifom/fifo[23][1]/q fifom_fifo_reg[23][1]/Q  -type DFF DFF
add mapped point fifom/fifo[38][3]/q fifom_fifo_reg[38][3]/Q  -type DFF DFF
add mapped point fifom/fifo[44][3]/q fifom_fifo_reg[44][3]/Q  -type DFF DFF
add mapped point fifom/fifo[17][6]/q fifom_fifo_reg[17][6]/Q  -type DFF DFF
add mapped point fifom/fifo[48][5]/q fifom_fifo_reg[48][5]/Q  -type DFF DFF
add mapped point fifom/fifo[8][6]/q fifom_fifo_reg[8][6]/Q  -type DFF DFF
add mapped point fifom/fifo[36][5]/q fifom_fifo_reg[36][5]/Q  -type DFF DFF
add mapped point fifom/fifo[56][6]/q fifom_fifo_reg[56][6]/Q  -type DFF DFF
add mapped point fifom/fifo[2][6]/q fifom_fifo_reg[2][6]/Q  -type DFF DFF
add mapped point fifom/fifo[48][6]/q fifom_fifo_reg[48][6]/Q  -type DFF DFF
add mapped point fifom/fifo[29][7]/q fifom_fifo_reg[29][7]/Q  -type DFF DFF
add mapped point fifom/fifo[2][2]/q fifom_fifo_reg[2][2]/Q  -type DFF DFF
add mapped point fifom/fifo[19][1]/q fifom_fifo_reg[19][1]/Q  -type DFF DFF
add mapped point fifom/fifo[56][2]/q fifom_fifo_reg[56][2]/Q  -type DFF DFF
add mapped point fifom/fifo[5][1]/q fifom_fifo_reg[5][1]/Q  -type DFF DFF
add mapped point fifom/fifo[50][6]/q fifom_fifo_reg[50][6]/Q  -type DFF DFF
add mapped point fifom/fifo[25][6]/q fifom_fifo_reg[25][6]/Q  -type DFF DFF
add mapped point fifom/fifo[3][7]/q fifom_fifo_reg[3][7]/Q  -type DFF DFF
add mapped point fifom/fifo[56][7]/q fifom_fifo_reg[56][7]/Q  -type DFF DFF
add mapped point fifom/fifo[36][1]/q fifom_fifo_reg[36][1]/Q  -type DFF DFF
add mapped point fifom/fifo[24][6]/q fifom_fifo_reg[24][6]/Q  -type DFF DFF
add mapped point fifom/fifo[13][2]/q fifom_fifo_reg[13][2]/Q  -type DFF DFF
add mapped point fifom/fifo[44][2]/q fifom_fifo_reg[44][2]/Q  -type DFF DFF
add mapped point fifom/fifo[1][1]/q fifom_fifo_reg[1][1]/Q  -type DFF DFF
add mapped point fifom/fifo[19][5]/q fifom_fifo_reg[19][5]/Q  -type DFF DFF
add mapped point fifom/fifo[13][3]/q fifom_fifo_reg[13][3]/Q  -type DFF DFF
add mapped point fifom/fifo[19][6]/q fifom_fifo_reg[19][6]/Q  -type DFF DFF
add mapped point fifom/fifo[62][7]/q fifom_fifo_reg[62][7]/Q  -type DFF DFF
add mapped point fifom/fifo[17][3]/q fifom_fifo_reg[17][3]/Q  -type DFF DFF
add mapped point fifom/fifo[5][3]/q fifom_fifo_reg[5][3]/Q  -type DFF DFF
add mapped point fifom/fifo[1][2]/q fifom_fifo_reg[1][2]/Q  -type DFF DFF
add mapped point fifom/fifo[1][4]/q fifom_fifo_reg[1][4]/Q  -type DFF DFF
add mapped point fifom/fifo[3][5]/q fifom_fifo_reg[3][5]/Q  -type DFF DFF
add mapped point fifom/fifo[21][5]/q fifom_fifo_reg[21][5]/Q  -type DFF DFF
add mapped point fifom/fifo[42][0]/q fifom_fifo_reg[42][0]/Q  -type DFF DFF
add mapped point fifom/fifo[12][6]/q fifom_fifo_reg[12][6]/Q  -type DFF DFF
add mapped point fifom/fifo[1][6]/q fifom_fifo_reg[1][6]/Q  -type DFF DFF
add mapped point fifom/fifo[9][1]/q fifom_fifo_reg[9][1]/Q  -type DFF DFF
add mapped point fifom/fifo[60][6]/q fifom_fifo_reg[60][6]/Q  -type DFF DFF
add mapped point fifom/fifo[42][1]/q fifom_fifo_reg[42][1]/Q  -type DFF DFF
add mapped point fifom/fifo[42][2]/q fifom_fifo_reg[42][2]/Q  -type DFF DFF
add mapped point fifom/fifo[42][3]/q fifom_fifo_reg[42][3]/Q  -type DFF DFF
add mapped point fifom/fifo[42][4]/q fifom_fifo_reg[42][4]/Q  -type DFF DFF
add mapped point fifom/fifo[42][5]/q fifom_fifo_reg[42][5]/Q  -type DFF DFF
add mapped point fifom/fifo[42][7]/q fifom_fifo_reg[42][7]/Q  -type DFF DFF
add mapped point fifom/fifo[26][6]/q fifom_fifo_reg[26][6]/Q  -type DFF DFF
add mapped point fifom/fifo[10][0]/q fifom_fifo_reg[10][0]/Q  -type DFF DFF
add mapped point fifom/fifo[10][1]/q fifom_fifo_reg[10][1]/Q  -type DFF DFF
add mapped point fifom/fifo[10][2]/q fifom_fifo_reg[10][2]/Q  -type DFF DFF
add mapped point fifom/fifo[10][3]/q fifom_fifo_reg[10][3]/Q  -type DFF DFF
add mapped point fifom/fifo[10][4]/q fifom_fifo_reg[10][4]/Q  -type DFF DFF
add mapped point fifom/fifo[10][5]/q fifom_fifo_reg[10][5]/Q  -type DFF DFF
add mapped point fifom/fifo[26][2]/q fifom_fifo_reg[26][2]/Q  -type DFF DFF
add mapped point fifom/fifo[10][7]/q fifom_fifo_reg[10][7]/Q  -type DFF DFF
add mapped point fifom/fifo[46][0]/q fifom_fifo_reg[46][0]/Q  -type DFF DFF
add mapped point fifom/fifo[46][1]/q fifom_fifo_reg[46][1]/Q  -type DFF DFF
add mapped point fifom/fifo[46][3]/q fifom_fifo_reg[46][3]/Q  -type DFF DFF
add mapped point fifom/fifo[46][4]/q fifom_fifo_reg[46][4]/Q  -type DFF DFF
add mapped point fifom/fifo[46][5]/q fifom_fifo_reg[46][5]/Q  -type DFF DFF
add mapped point fifom/fifo[46][7]/q fifom_fifo_reg[46][7]/Q  -type DFF DFF
add mapped point fifom/fifo[58][0]/q fifom_fifo_reg[58][0]/Q  -type DFF DFF
add mapped point fifom/fifo[58][1]/q fifom_fifo_reg[58][1]/Q  -type DFF DFF
add mapped point fifom/fifo[58][3]/q fifom_fifo_reg[58][3]/Q  -type DFF DFF
add mapped point fifom/fifo[58][4]/q fifom_fifo_reg[58][4]/Q  -type DFF DFF
add mapped point fifom/fifo[58][5]/q fifom_fifo_reg[58][5]/Q  -type DFF DFF
add mapped point fifom/fifo[40][2]/q fifom_fifo_reg[40][2]/Q  -type DFF DFF
add mapped point fifom/fifo[58][7]/q fifom_fifo_reg[58][7]/Q  -type DFF DFF
add mapped point fifom/fifo[34][0]/q fifom_fifo_reg[34][0]/Q  -type DFF DFF
add mapped point fifom/fifo[34][1]/q fifom_fifo_reg[34][1]/Q  -type DFF DFF
add mapped point fifom/fifo[34][2]/q fifom_fifo_reg[34][2]/Q  -type DFF DFF
add mapped point fifom/fifo[34][3]/q fifom_fifo_reg[34][3]/Q  -type DFF DFF
add mapped point fifom/fifo[34][4]/q fifom_fifo_reg[34][4]/Q  -type DFF DFF
add mapped point fifom/fifo[34][5]/q fifom_fifo_reg[34][5]/Q  -type DFF DFF
add mapped point fifom/fifo[34][7]/q fifom_fifo_reg[34][7]/Q  -type DFF DFF
add mapped point fifom/fifo[40][0]/q fifom_fifo_reg[40][0]/Q  -type DFF DFF
add mapped point fifom/fifo[40][1]/q fifom_fifo_reg[40][1]/Q  -type DFF DFF
add mapped point fifom/fifo[40][3]/q fifom_fifo_reg[40][3]/Q  -type DFF DFF
add mapped point fifom/fifo[40][4]/q fifom_fifo_reg[40][4]/Q  -type DFF DFF
add mapped point fifom/fifo[40][5]/q fifom_fifo_reg[40][5]/Q  -type DFF DFF
add mapped point fifom/fifo[40][7]/q fifom_fifo_reg[40][7]/Q  -type DFF DFF
add mapped point fifom/fifo[26][0]/q fifom_fifo_reg[26][0]/Q  -type DFF DFF
add mapped point fifom/fifo[26][1]/q fifom_fifo_reg[26][1]/Q  -type DFF DFF
add mapped point fifom/fifo[26][3]/q fifom_fifo_reg[26][3]/Q  -type DFF DFF
add mapped point fifom/fifo[26][4]/q fifom_fifo_reg[26][4]/Q  -type DFF DFF
add mapped point fifom/fifo[26][5]/q fifom_fifo_reg[26][5]/Q  -type DFF DFF
add mapped point fifom/fifo[26][7]/q fifom_fifo_reg[26][7]/Q  -type DFF DFF
add mapped point fifom/fifo[40][6]/q fifom_fifo_reg[40][6]/Q  -type DFF DFF
add mapped point fifom/fifo[58][2]/q fifom_fifo_reg[58][2]/Q  -type DFF DFF
add mapped point fifom/fifo[62][1]/q fifom_fifo_reg[62][1]/Q  -type DFF DFF
add mapped point fifom/fifo[62][2]/q fifom_fifo_reg[62][2]/Q  -type DFF DFF
add mapped point fifom/fifo[62][3]/q fifom_fifo_reg[62][3]/Q  -type DFF DFF
add mapped point fifom/fifo[62][4]/q fifom_fifo_reg[62][4]/Q  -type DFF DFF
add mapped point fifom/fifo[62][5]/q fifom_fifo_reg[62][5]/Q  -type DFF DFF
add mapped point fifom/fifo[62][6]/q fifom_fifo_reg[62][6]/Q  -type DFF DFF
add mapped point fifom/fifo[62][0]/q fifom_fifo_reg[62][0]/Q  -type DFF DFF
add mapped point fifom/fifo[34][6]/q fifom_fifo_reg[34][6]/Q  -type DFF DFF
add mapped point fifom/fifo[58][6]/q fifom_fifo_reg[58][6]/Q  -type DFF DFF
add mapped point fifom/fifo[2][0]/q fifom_fifo_reg[2][0]/Q  -type DFF DFF
add mapped point fifom/fifo[2][1]/q fifom_fifo_reg[2][1]/Q  -type DFF DFF
add mapped point fifom/fifo[2][3]/q fifom_fifo_reg[2][3]/Q  -type DFF DFF
add mapped point fifom/fifo[2][4]/q fifom_fifo_reg[2][4]/Q  -type DFF DFF
add mapped point fifom/fifo[2][5]/q fifom_fifo_reg[2][5]/Q  -type DFF DFF
add mapped point fifom/fifo[2][7]/q fifom_fifo_reg[2][7]/Q  -type DFF DFF
add mapped point fifom/fifo[8][0]/q fifom_fifo_reg[8][0]/Q  -type DFF DFF
add mapped point fifom/fifo[8][1]/q fifom_fifo_reg[8][1]/Q  -type DFF DFF
add mapped point fifom/fifo[8][2]/q fifom_fifo_reg[8][2]/Q  -type DFF DFF
add mapped point fifom/fifo[8][3]/q fifom_fifo_reg[8][3]/Q  -type DFF DFF
add mapped point fifom/fifo[8][5]/q fifom_fifo_reg[8][5]/Q  -type DFF DFF
add mapped point fifom/fifo[8][4]/q fifom_fifo_reg[8][4]/Q  -type DFF DFF
add mapped point fifom/fifo[8][7]/q fifom_fifo_reg[8][7]/Q  -type DFF DFF
add mapped point fifom/fifo[38][1]/q fifom_fifo_reg[38][1]/Q  -type DFF DFF
add mapped point fifom/fifo[38][2]/q fifom_fifo_reg[38][2]/Q  -type DFF DFF
add mapped point fifom/fifo[38][4]/q fifom_fifo_reg[38][4]/Q  -type DFF DFF
add mapped point fifom/fifo[38][5]/q fifom_fifo_reg[38][5]/Q  -type DFF DFF
add mapped point fifom/fifo[38][6]/q fifom_fifo_reg[38][6]/Q  -type DFF DFF
add mapped point fifom/fifo[38][0]/q fifom_fifo_reg[38][0]/Q  -type DFF DFF
add mapped point fifom/fifo[44][0]/q fifom_fifo_reg[44][0]/Q  -type DFF DFF
add mapped point fifom/fifo[44][1]/q fifom_fifo_reg[44][1]/Q  -type DFF DFF
add mapped point fifom/fifo[44][5]/q fifom_fifo_reg[44][5]/Q  -type DFF DFF
add mapped point fifom/fifo[44][7]/q fifom_fifo_reg[44][7]/Q  -type DFF DFF
add mapped point fifom/fifo[14][0]/q fifom_fifo_reg[14][0]/Q  -type DFF DFF
add mapped point fifom/fifo[14][1]/q fifom_fifo_reg[14][1]/Q  -type DFF DFF
add mapped point fifom/fifo[14][3]/q fifom_fifo_reg[14][3]/Q  -type DFF DFF
add mapped point fifom/fifo[14][4]/q fifom_fifo_reg[14][4]/Q  -type DFF DFF
add mapped point fifom/fifo[14][5]/q fifom_fifo_reg[14][5]/Q  -type DFF DFF
add mapped point fifom/fifo[14][7]/q fifom_fifo_reg[14][7]/Q  -type DFF DFF
add mapped point fifom/fifo[46][6]/q fifom_fifo_reg[46][6]/Q  -type DFF DFF
add mapped point fifom/fifo[24][2]/q fifom_fifo_reg[24][2]/Q  -type DFF DFF
add mapped point fifom/fifo[50][0]/q fifom_fifo_reg[50][0]/Q  -type DFF DFF
add mapped point fifom/fifo[50][1]/q fifom_fifo_reg[50][1]/Q  -type DFF DFF
add mapped point fifom/fifo[50][3]/q fifom_fifo_reg[50][3]/Q  -type DFF DFF
add mapped point fifom/fifo[50][4]/q fifom_fifo_reg[50][4]/Q  -type DFF DFF
add mapped point fifom/fifo[50][5]/q fifom_fifo_reg[50][5]/Q  -type DFF DFF
add mapped point fifom/fifo[50][7]/q fifom_fifo_reg[50][7]/Q  -type DFF DFF
add mapped point fifom/fifo[56][0]/q fifom_fifo_reg[56][0]/Q  -type DFF DFF
add mapped point fifom/fifo[56][1]/q fifom_fifo_reg[56][1]/Q  -type DFF DFF
add mapped point fifom/fifo[56][3]/q fifom_fifo_reg[56][3]/Q  -type DFF DFF
add mapped point fifom/fifo[56][4]/q fifom_fifo_reg[56][4]/Q  -type DFF DFF
add mapped point fifom/fifo[56][5]/q fifom_fifo_reg[56][5]/Q  -type DFF DFF
add mapped point fifom/fifo[46][2]/q fifom_fifo_reg[46][2]/Q  -type DFF DFF
add mapped point fifom/fifo[10][6]/q fifom_fifo_reg[10][6]/Q  -type DFF DFF
add mapped point fifom/fifo[32][1]/q fifom_fifo_reg[32][1]/Q  -type DFF DFF
add mapped point fifom/fifo[32][2]/q fifom_fifo_reg[32][2]/Q  -type DFF DFF
add mapped point fifom/fifo[32][3]/q fifom_fifo_reg[32][3]/Q  -type DFF DFF
add mapped point fifom/fifo[32][4]/q fifom_fifo_reg[32][4]/Q  -type DFF DFF
add mapped point fifom/fifo[32][5]/q fifom_fifo_reg[32][5]/Q  -type DFF DFF
add mapped point fifom/fifo[32][6]/q fifom_fifo_reg[32][6]/Q  -type DFF DFF
add mapped point fifom/fifo[32][0]/q fifom_fifo_reg[32][0]/Q  -type DFF DFF
add mapped point fifom/fifo[30][0]/q fifom_fifo_reg[30][0]/Q  -type DFF DFF
add mapped point fifom/fifo[30][1]/q fifom_fifo_reg[30][1]/Q  -type DFF DFF
add mapped point fifom/fifo[30][3]/q fifom_fifo_reg[30][3]/Q  -type DFF DFF
add mapped point fifom/fifo[30][4]/q fifom_fifo_reg[30][4]/Q  -type DFF DFF
add mapped point fifom/fifo[30][5]/q fifom_fifo_reg[30][5]/Q  -type DFF DFF
add mapped point fifom/fifo[30][7]/q fifom_fifo_reg[30][7]/Q  -type DFF DFF
add mapped point fifom/fifo[12][0]/q fifom_fifo_reg[12][0]/Q  -type DFF DFF
add mapped point fifom/fifo[12][1]/q fifom_fifo_reg[12][1]/Q  -type DFF DFF
add mapped point fifom/fifo[12][3]/q fifom_fifo_reg[12][3]/Q  -type DFF DFF
add mapped point fifom/fifo[12][4]/q fifom_fifo_reg[12][4]/Q  -type DFF DFF
add mapped point fifom/fifo[12][5]/q fifom_fifo_reg[12][5]/Q  -type DFF DFF
add mapped point fifom/fifo[12][7]/q fifom_fifo_reg[12][7]/Q  -type DFF DFF
add mapped point fifom/fifo[18][0]/q fifom_fifo_reg[18][0]/Q  -type DFF DFF
add mapped point fifom/fifo[18][1]/q fifom_fifo_reg[18][1]/Q  -type DFF DFF
add mapped point fifom/fifo[18][2]/q fifom_fifo_reg[18][2]/Q  -type DFF DFF
add mapped point fifom/fifo[18][3]/q fifom_fifo_reg[18][3]/Q  -type DFF DFF
add mapped point fifom/fifo[18][4]/q fifom_fifo_reg[18][4]/Q  -type DFF DFF
add mapped point fifom/fifo[18][5]/q fifom_fifo_reg[18][5]/Q  -type DFF DFF
add mapped point fifom/fifo[18][7]/q fifom_fifo_reg[18][7]/Q  -type DFF DFF
add mapped point fifom/fifo[24][0]/q fifom_fifo_reg[24][0]/Q  -type DFF DFF
add mapped point fifom/fifo[24][1]/q fifom_fifo_reg[24][1]/Q  -type DFF DFF
add mapped point fifom/fifo[24][3]/q fifom_fifo_reg[24][3]/Q  -type DFF DFF
add mapped point fifom/fifo[24][4]/q fifom_fifo_reg[24][4]/Q  -type DFF DFF
add mapped point fifom/fifo[24][5]/q fifom_fifo_reg[24][5]/Q  -type DFF DFF
add mapped point fifom/fifo[24][7]/q fifom_fifo_reg[24][7]/Q  -type DFF DFF
add mapped point fifom/fifo[54][6]/q fifom_fifo_reg[54][6]/Q  -type DFF DFF
add mapped point fifom/fifo[42][6]/q fifom_fifo_reg[42][6]/Q  -type DFF DFF
add mapped point fifom/fifo[6][0]/q fifom_fifo_reg[6][0]/Q  -type DFF DFF
add mapped point fifom/fifo[6][1]/q fifom_fifo_reg[6][1]/Q  -type DFF DFF
add mapped point fifom/fifo[6][4]/q fifom_fifo_reg[6][4]/Q  -type DFF DFF
add mapped point fifom/fifo[6][3]/q fifom_fifo_reg[6][3]/Q  -type DFF DFF
add mapped point fifom/fifo[6][5]/q fifom_fifo_reg[6][5]/Q  -type DFF DFF
add mapped point fifom/fifo[6][7]/q fifom_fifo_reg[6][7]/Q  -type DFF DFF
add mapped point fifom/fifo[54][0]/q fifom_fifo_reg[54][0]/Q  -type DFF DFF
add mapped point fifom/fifo[54][1]/q fifom_fifo_reg[54][1]/Q  -type DFF DFF
add mapped point fifom/fifo[54][3]/q fifom_fifo_reg[54][3]/Q  -type DFF DFF
add mapped point fifom/fifo[54][4]/q fifom_fifo_reg[54][4]/Q  -type DFF DFF
add mapped point fifom/fifo[54][5]/q fifom_fifo_reg[54][5]/Q  -type DFF DFF
add mapped point fifom/fifo[60][0]/q fifom_fifo_reg[60][0]/Q  -type DFF DFF
add mapped point fifom/fifo[60][1]/q fifom_fifo_reg[60][1]/Q  -type DFF DFF
add mapped point fifom/fifo[60][2]/q fifom_fifo_reg[60][2]/Q  -type DFF DFF
add mapped point fifom/fifo[60][3]/q fifom_fifo_reg[60][3]/Q  -type DFF DFF
add mapped point fifom/fifo[60][4]/q fifom_fifo_reg[60][4]/Q  -type DFF DFF
add mapped point fifom/fifo[60][5]/q fifom_fifo_reg[60][5]/Q  -type DFF DFF
add mapped point fifom/fifo[21][1]/q fifom_fifo_reg[21][1]/Q  -type DFF DFF
add mapped point fifom/fifo[54][7]/q fifom_fifo_reg[54][7]/Q  -type DFF DFF
add mapped point fifom/fifo[60][7]/q fifom_fifo_reg[60][7]/Q  -type DFF DFF
add mapped point fifom/fifo[9][2]/q fifom_fifo_reg[9][2]/Q  -type DFF DFF
add mapped point fifom/fifo[17][1]/q fifom_fifo_reg[17][1]/Q  -type DFF DFF
add mapped point fifom/fifo[17][2]/q fifom_fifo_reg[17][2]/Q  -type DFF DFF
add mapped point fifom/fifo[17][4]/q fifom_fifo_reg[17][4]/Q  -type DFF DFF
add mapped point fifom/fifo[17][5]/q fifom_fifo_reg[17][5]/Q  -type DFF DFF
add mapped point fifom/fifo[17][0]/q fifom_fifo_reg[17][0]/Q  -type DFF DFF
add mapped point fifom/fifo[17][7]/q fifom_fifo_reg[17][7]/Q  -type DFF DFF
add mapped point fifom/fifo[19][0]/q fifom_fifo_reg[19][0]/Q  -type DFF DFF
add mapped point fifom/fifo[19][3]/q fifom_fifo_reg[19][3]/Q  -type DFF DFF
add mapped point fifom/fifo[19][4]/q fifom_fifo_reg[19][4]/Q  -type DFF DFF
add mapped point fifom/fifo[44][4]/q fifom_fifo_reg[44][4]/Q  -type DFF DFF
add mapped point fifom/fifo[19][2]/q fifom_fifo_reg[19][2]/Q  -type DFF DFF
add mapped point fifom/fifo[21][0]/q fifom_fifo_reg[21][0]/Q  -type DFF DFF
add mapped point fifom/fifo[21][3]/q fifom_fifo_reg[21][3]/Q  -type DFF DFF
add mapped point fifom/fifo[21][4]/q fifom_fifo_reg[21][4]/Q  -type DFF DFF
add mapped point fifom/fifo[21][7]/q fifom_fifo_reg[21][7]/Q  -type DFF DFF
add mapped point fifom/fifo[21][2]/q fifom_fifo_reg[21][2]/Q  -type DFF DFF
add mapped point fifom/fifo[23][0]/q fifom_fifo_reg[23][0]/Q  -type DFF DFF
add mapped point fifom/fifo[23][2]/q fifom_fifo_reg[23][2]/Q  -type DFF DFF
add mapped point fifom/fifo[23][3]/q fifom_fifo_reg[23][3]/Q  -type DFF DFF
add mapped point fifom/fifo[23][4]/q fifom_fifo_reg[23][4]/Q  -type DFF DFF
add mapped point fifom/fifo[23][6]/q fifom_fifo_reg[23][6]/Q  -type DFF DFF
add mapped point fifom/fifo[23][7]/q fifom_fifo_reg[23][7]/Q  -type DFF DFF
add mapped point fifom/fifo[25][0]/q fifom_fifo_reg[25][0]/Q  -type DFF DFF
add mapped point fifom/fifo[25][4]/q fifom_fifo_reg[25][4]/Q  -type DFF DFF
add mapped point fifom/fifo[25][5]/q fifom_fifo_reg[25][5]/Q  -type DFF DFF
add mapped point fifom/fifo[25][2]/q fifom_fifo_reg[25][2]/Q  -type DFF DFF
add mapped point fifom/fifo[25][7]/q fifom_fifo_reg[25][7]/Q  -type DFF DFF
add mapped point fifom/fifo[25][3]/q fifom_fifo_reg[25][3]/Q  -type DFF DFF
add mapped point fifom/fifo[29][0]/q fifom_fifo_reg[29][0]/Q  -type DFF DFF
add mapped point fifom/fifo[29][1]/q fifom_fifo_reg[29][1]/Q  -type DFF DFF
add mapped point fifom/fifo[29][5]/q fifom_fifo_reg[29][5]/Q  -type DFF DFF
add mapped point fifom/fifo[29][6]/q fifom_fifo_reg[29][6]/Q  -type DFF DFF
add mapped point fifom/fifo[29][3]/q fifom_fifo_reg[29][3]/Q  -type DFF DFF
add mapped point fifom/fifo[29][4]/q fifom_fifo_reg[29][4]/Q  -type DFF DFF
add mapped point fifom/fifo[31][0]/q fifom_fifo_reg[31][0]/Q  -type DFF DFF
add mapped point fifom/fifo[31][2]/q fifom_fifo_reg[31][2]/Q  -type DFF DFF
add mapped point fifom/fifo[31][3]/q fifom_fifo_reg[31][3]/Q  -type DFF DFF
add mapped point fifom/fifo[31][4]/q fifom_fifo_reg[31][4]/Q  -type DFF DFF
add mapped point fifom/fifo[31][6]/q fifom_fifo_reg[31][6]/Q  -type DFF DFF
add mapped point fifom/fifo[31][7]/q fifom_fifo_reg[31][7]/Q  -type DFF DFF
add mapped point fifom/fifo[36][0]/q fifom_fifo_reg[36][0]/Q  -type DFF DFF
add mapped point fifom/fifo[36][3]/q fifom_fifo_reg[36][3]/Q  -type DFF DFF
add mapped point fifom/fifo[36][4]/q fifom_fifo_reg[36][4]/Q  -type DFF DFF
add mapped point fifom/fifo[19][7]/q fifom_fifo_reg[19][7]/Q  -type DFF DFF
add mapped point fifom/fifo[36][7]/q fifom_fifo_reg[36][7]/Q  -type DFF DFF
add mapped point fifom/fifo[36][2]/q fifom_fifo_reg[36][2]/Q  -type DFF DFF
add mapped point fifom/fifo[18][6]/q fifom_fifo_reg[18][6]/Q  -type DFF DFF
add mapped point fifom/fifo[48][0]/q fifom_fifo_reg[48][0]/Q  -type DFF DFF
add mapped point fifom/fifo[48][3]/q fifom_fifo_reg[48][3]/Q  -type DFF DFF
add mapped point fifom/fifo[48][4]/q fifom_fifo_reg[48][4]/Q  -type DFF DFF
add mapped point fifom/fifo[48][7]/q fifom_fifo_reg[48][7]/Q  -type DFF DFF
add mapped point fifom/fifo[48][2]/q fifom_fifo_reg[48][2]/Q  -type DFF DFF
add mapped point fifom/fifo[1][0]/q fifom_fifo_reg[1][0]/Q  -type DFF DFF
add mapped point fifom/fifo[1][3]/q fifom_fifo_reg[1][3]/Q  -type DFF DFF
add mapped point fifom/fifo[12][2]/q fifom_fifo_reg[12][2]/Q  -type DFF DFF
add mapped point fifom/fifo[1][5]/q fifom_fifo_reg[1][5]/Q  -type DFF DFF
add mapped point fifom/fifo[1][7]/q fifom_fifo_reg[1][7]/Q  -type DFF DFF
add mapped point fifom/fifo[3][0]/q fifom_fifo_reg[3][0]/Q  -type DFF DFF
add mapped point fifom/fifo[3][3]/q fifom_fifo_reg[3][3]/Q  -type DFF DFF
add mapped point fifom/fifo[3][4]/q fifom_fifo_reg[3][4]/Q  -type DFF DFF
add mapped point fifom/fifo[30][6]/q fifom_fifo_reg[30][6]/Q  -type DFF DFF
add mapped point fifom/fifo[3][6]/q fifom_fifo_reg[3][6]/Q  -type DFF DFF
add mapped point fifom/fifo[3][2]/q fifom_fifo_reg[3][2]/Q  -type DFF DFF
add mapped point fifom/fifo[5][0]/q fifom_fifo_reg[5][0]/Q  -type DFF DFF
add mapped point fifom/fifo[30][2]/q fifom_fifo_reg[30][2]/Q  -type DFF DFF
add mapped point fifom/fifo[5][2]/q fifom_fifo_reg[5][2]/Q  -type DFF DFF
add mapped point fifom/fifo[32][7]/q fifom_fifo_reg[32][7]/Q  -type DFF DFF
add mapped point fifom/fifo[5][6]/q fifom_fifo_reg[5][6]/Q  -type DFF DFF
add mapped point fifom/fifo[5][7]/q fifom_fifo_reg[5][7]/Q  -type DFF DFF
add mapped point fifom/fifo[5][4]/q fifom_fifo_reg[5][4]/Q  -type DFF DFF
add mapped point fifom/fifo[5][5]/q fifom_fifo_reg[5][5]/Q  -type DFF DFF
add mapped point fifom/fifo[7][0]/q fifom_fifo_reg[7][0]/Q  -type DFF DFF
add mapped point fifom/fifo[7][2]/q fifom_fifo_reg[7][2]/Q  -type DFF DFF
add mapped point fifom/fifo[7][4]/q fifom_fifo_reg[7][4]/Q  -type DFF DFF
add mapped point fifom/fifo[7][5]/q fifom_fifo_reg[7][5]/Q  -type DFF DFF
add mapped point fifom/fifo[7][3]/q fifom_fifo_reg[7][3]/Q  -type DFF DFF
add mapped point fifom/fifo[7][7]/q fifom_fifo_reg[7][7]/Q  -type DFF DFF
add mapped point fifom/fifo[9][0]/q fifom_fifo_reg[9][0]/Q  -type DFF DFF
add mapped point fifom/fifo[9][7]/q fifom_fifo_reg[9][7]/Q  -type DFF DFF
add mapped point fifom/fifo[9][4]/q fifom_fifo_reg[9][4]/Q  -type DFF DFF
add mapped point fifom/fifo[9][6]/q fifom_fifo_reg[9][6]/Q  -type DFF DFF
add mapped point fifom/fifo[9][3]/q fifom_fifo_reg[9][3]/Q  -type DFF DFF
add mapped point fifom/fifo[0][2]/q fifom_fifo_reg[0][2]/Q  -type DFF DFF
add mapped point fifom/fifo[0][1]/q fifom_fifo_reg[0][1]/Q  -type DFF DFF
add mapped point fifom/fifo[0][4]/q fifom_fifo_reg[0][4]/Q  -type DFF DFF
add mapped point fifom/fifo[0][5]/q fifom_fifo_reg[0][5]/Q  -type DFF DFF
add mapped point fifom/fifo[0][6]/q fifom_fifo_reg[0][6]/Q  -type DFF DFF
add mapped point fifom/fifo[0][7]/q fifom_fifo_reg[0][7]/Q  -type DFF DFF
add mapped point fifom/fifo[13][0]/q fifom_fifo_reg[13][0]/Q  -type DFF DFF
add mapped point fifom/fifo[13][1]/q fifom_fifo_reg[13][1]/Q  -type DFF DFF
add mapped point fifom/fifo[13][4]/q fifom_fifo_reg[13][4]/Q  -type DFF DFF
add mapped point fifom/fifo[13][5]/q fifom_fifo_reg[13][5]/Q  -type DFF DFF
add mapped point fifom/fifo[13][7]/q fifom_fifo_reg[13][7]/Q  -type DFF DFF
add mapped point fifom/fifo[0][3]/q fifom_fifo_reg[0][3]/Q  -type DFF DFF
add mapped point fifom/fifo[25][1]/q fifom_fifo_reg[25][1]/Q  -type DFF DFF
add mapped point fifom/fifo[54][2]/q fifom_fifo_reg[54][2]/Q  -type DFF DFF
add mapped point rptr_h/b_rptr[2]/q rptr_h_b_rptr_reg[2]/Q  -type DFF DFF
add mapped point rptr_h/b_rptr[1]/q rptr_h_b_rptr_reg[1]/Q  -type DFF DFF
add mapped point wptr_h/b_wptr[1]/q wptr_h_b_wptr_reg[1]/Q  -type DFF DFF
add mapped point wptr_h/b_wptr[0]/q wptr_h_b_wptr_reg[0]/Q  -type DFF DFF
add mapped point rptr_h/b_rptr[0]/q rptr_h_b_rptr_reg[0]/Q  -type DFF DFF
add mapped point sync_wptr/dout[6]/q sync_wptr_dout_reg[6]/Q  -type DFF DFF
add mapped point sync_rptr/dout[6]/q sync_rptr_dout_reg[6]/Q  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
